FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS=linux
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o /out/watchtrace-worker ./cmd/worker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/watchtrace-worker /watchtrace-worker
VOLUME ["/var/lib/watchtrace-worker"]
USER nonroot:nonroot
ENTRYPOINT ["/watchtrace-worker"]
