// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeEmailVerification = `-- name: CompleteEmailVerification :one
WITH consumed AS (
    UPDATE user_action_tokens
    SET used_at = CURRENT_TIMESTAMP
    WHERE id = $1::text::uuid
      AND purpose = 'email_verification'
      AND used_at IS NULL
    RETURNING user_id
)
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
FROM consumed
WHERE users.id = consumed.user_id
RETURNING
    users.id::text AS id,
    users.email,
    (users.email_verified_at IS NOT NULL)::boolean AS email_verified
`

type CompleteEmailVerificationRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

func (q *Queries) CompleteEmailVerification(ctx context.Context, tokenID string) (CompleteEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, completeEmailVerification, tokenID)
	var i CompleteEmailVerificationRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const completePasswordReset = `-- name: CompletePasswordReset :execrows
WITH consumed AS (
    UPDATE user_action_tokens
    SET used_at = CURRENT_TIMESTAMP
    WHERE id = $2::text::uuid
      AND purpose = 'password_reset'
      AND used_at IS NULL
    RETURNING user_id
)
UPDATE users
SET password_hash = $1,
    updated_at = CURRENT_TIMESTAMP
FROM consumed
WHERE users.id = consumed.user_id
`

type CompletePasswordResetParams struct {
	PasswordHash string
	TokenID      string
}

func (q *Queries) CompletePasswordReset(ctx context.Context, arg CompletePasswordResetParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePasswordReset, arg.PasswordHash, arg.TokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (user_id, family_id, token_digest, expires_at)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4
)
`

type CreateAuthSessionParams struct {
	UserID      string
	FamilyID    string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.UserID,
		arg.FamilyID,
		arg.TokenDigest,
		arg.ExpiresAt,
	)
	return err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec
INSERT INTO user_action_tokens (user_id, purpose, token_digest, expires_at)
VALUES (
    $1::text::uuid,
    'email_verification',
    $2,
    $3
)
`

type CreateEmailVerificationTokenParams struct {
	UserID      string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO user_action_tokens (user_id, purpose, token_digest, expires_at)
VALUES (
    $1::text::uuid,
    'password_reset',
    $2,
    $3
)
`

type CreatePasswordResetTokenParams struct {
	UserID      string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	return err
}

const createRefreshTokenFamily = `-- name: CreateRefreshTokenFamily :one
INSERT INTO refresh_tokens (user_id, family_id, token_digest, expires_at)
VALUES (
    $1::text::uuid,
    gen_random_uuid(),
    $2,
    $3
)
RETURNING id::text AS id, family_id::text AS family_id
`

type CreateRefreshTokenFamilyParams struct {
	UserID      string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

type CreateRefreshTokenFamilyRow struct {
	ID       string
	FamilyID string
}

func (q *Queries) CreateRefreshTokenFamily(ctx context.Context, arg CreateRefreshTokenFamilyParams) (CreateRefreshTokenFamilyRow, error) {
	row := q.db.QueryRow(ctx, createRefreshTokenFamily, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	var i CreateRefreshTokenFamilyRow
	err := row.Scan(&i.ID, &i.FamilyID)
	return i, err
}

const createRotatedRefreshToken = `-- name: CreateRotatedRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_digest, expires_at)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4
)
RETURNING id::text AS id
`

type CreateRotatedRefreshTokenParams struct {
	UserID      string
	FamilyID    string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateRotatedRefreshToken(ctx context.Context, arg CreateRotatedRefreshTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, createRotatedRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenDigest,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id::text AS id, email, (email_verified_at IS NOT NULL)::boolean AS email_verified
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const deleteExpiredOrRevokedAccessTokens = `-- name: DeleteExpiredOrRevokedAccessTokens :execrows
WITH candidates AS (
    SELECT id
    FROM auth_sessions
    WHERE expires_at <= CURRENT_TIMESTAMP
       OR revoked_at IS NOT NULL
    ORDER BY COALESCE(revoked_at, expires_at), id
    LIMIT $1
)
DELETE FROM auth_sessions
USING candidates
WHERE auth_sessions.id = candidates.id
`

func (q *Queries) DeleteExpiredOrRevokedAccessTokens(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOrRevokedAccessTokens, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshTokenFamilies = `-- name: DeleteExpiredRefreshTokenFamilies :execrows
WITH candidates AS (
    SELECT family_id
    FROM refresh_tokens
    GROUP BY family_id
    HAVING max(expires_at) <= CURRENT_TIMESTAMP
    ORDER BY max(expires_at), family_id
    LIMIT $1
)
DELETE FROM refresh_tokens
USING candidates
WHERE refresh_tokens.family_id = candidates.family_id
`

func (q *Queries) DeleteExpiredRefreshTokenFamilies(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokenFamilies, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByAuthSession = `-- name: GetUserByAuthSession :one
SELECT
    users.id::text AS id,
    users.email,
    (users.email_verified_at IS NOT NULL)::boolean AS email_verified
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_digest = $1
  AND auth_sessions.expires_at > CURRENT_TIMESTAMP
  AND auth_sessions.revoked_at IS NULL
`

type GetUserByAuthSessionRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

func (q *Queries) GetUserByAuthSession(ctx context.Context, tokenDigest []byte) (GetUserByAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSession, tokenDigest)
	var i GetUserByAuthSessionRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    id::text AS id,
    email,
    password_hash,
    (email_verified_at IS NOT NULL)::boolean AS email_verified
FROM users
WHERE lower(btrim(email)) = $1
`

type GetUserForLoginRow struct {
	ID            string
	Email         string
	PasswordHash  string
	EmailVerified bool
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const getUserForPasswordReset = `-- name: GetUserForPasswordReset :one
SELECT id::text AS id, email
FROM users
WHERE lower(btrim(email)) = $1
`

type GetUserForPasswordResetRow struct {
	ID    string
	Email string
}

func (q *Queries) GetUserForPasswordReset(ctx context.Context, email string) (GetUserForPasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getUserForPasswordReset, email)
	var i GetUserForPasswordResetRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const invalidateActivePasswordResetTokens = `-- name: InvalidateActivePasswordResetTokens :execrows
UPDATE user_action_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE user_id = $1::text::uuid
  AND purpose = 'password_reset'
  AND used_at IS NULL
`

func (q *Queries) InvalidateActivePasswordResetTokens(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActivePasswordResetTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockEmailVerificationToken = `-- name: LockEmailVerificationToken :one
SELECT
    user_action_tokens.id::text AS id,
    user_action_tokens.expires_at,
    user_action_tokens.used_at
FROM user_action_tokens
WHERE user_action_tokens.purpose = 'email_verification'
  AND user_action_tokens.token_digest = $1
FOR UPDATE
`

type LockEmailVerificationTokenRow struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) LockEmailVerificationToken(ctx context.Context, tokenDigest []byte) (LockEmailVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, lockEmailVerificationToken, tokenDigest)
	var i LockEmailVerificationTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.UsedAt)
	return i, err
}

const lockPasswordResetToken = `-- name: LockPasswordResetToken :one
SELECT
    user_action_tokens.id::text AS id,
    user_action_tokens.user_id::text AS user_id,
    user_action_tokens.expires_at,
    user_action_tokens.used_at
FROM user_action_tokens
WHERE user_action_tokens.purpose = 'password_reset'
  AND user_action_tokens.token_digest = $1
FOR UPDATE
`

type LockPasswordResetTokenRow struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) LockPasswordResetToken(ctx context.Context, tokenDigest []byte) (LockPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetToken, tokenDigest)
	var i LockPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const lockRefreshTokenForRotation = `-- name: LockRefreshTokenForRotation :one
SELECT
    refresh_tokens.id::text AS id,
    refresh_tokens.user_id::text AS user_id,
    refresh_tokens.family_id::text AS family_id,
    refresh_tokens.expires_at,
    refresh_tokens.rotated_at,
    refresh_tokens.revoked_at,
    users.email,
    (users.email_verified_at IS NOT NULL)::boolean AS email_verified
FROM refresh_tokens
JOIN users ON users.id = refresh_tokens.user_id
WHERE refresh_tokens.token_digest = $1
FOR UPDATE OF refresh_tokens
`

type LockRefreshTokenForRotationRow struct {
	ID            string
	UserID        string
	FamilyID      string
	ExpiresAt     pgtype.Timestamptz
	RotatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	Email         string
	EmailVerified bool
}

func (q *Queries) LockRefreshTokenForRotation(ctx context.Context, tokenDigest []byte) (LockRefreshTokenForRotationRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshTokenForRotation, tokenDigest)
	var i LockRefreshTokenForRotationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :execrows
UPDATE refresh_tokens
SET rotated_at = CURRENT_TIMESTAMP,
    replaced_by_id = $1::text::uuid
WHERE id = $2::text::uuid
  AND rotated_at IS NULL
  AND revoked_at IS NULL
`

type MarkRefreshTokenRotatedParams struct {
	ReplacedByID string
	ID           string
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.ReplacedByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessTokenFamily = `-- name: RevokeAccessTokenFamily :execrows
UPDATE auth_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE family_id = $1::text::uuid
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAccessTokenFamily(ctx context.Context, familyID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokenFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessTokensForUser = `-- name: RevokeAccessTokensForUser :execrows
UPDATE auth_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1::text::uuid
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAccessTokensForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE family_id = $1::text::uuid
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :execrows
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1::text::uuid
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
