// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (user_id, token_digest, expires_at)
VALUES ($1::text::uuid, $2, $3)
`

type CreateAuthSessionParams struct {
	UserID      string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id::text AS id, email, (email_verified_at IS NOT NULL)::boolean AS email_verified
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const getUserByAuthSession = `-- name: GetUserByAuthSession :one
SELECT
    users.id::text AS id,
    users.email,
    (users.email_verified_at IS NOT NULL)::boolean AS email_verified
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_digest = $1
  AND auth_sessions.expires_at > CURRENT_TIMESTAMP
`

type GetUserByAuthSessionRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

func (q *Queries) GetUserByAuthSession(ctx context.Context, tokenDigest []byte) (GetUserByAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSession, tokenDigest)
	var i GetUserByAuthSessionRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    id::text AS id,
    email,
    password_hash,
    (email_verified_at IS NOT NULL)::boolean AS email_verified
FROM users
WHERE lower(btrim(email)) = $1
`

type GetUserForLoginRow struct {
	ID            string
	Email         string
	PasswordHash  string
	EmailVerified bool
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}
