// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backend.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeBackendMonitor = `-- name: AuthorizeBackendMonitor :one
SELECT monitors.organization_id::text AS organization_id, org_members.role
FROM monitors
JOIN organizations
  ON organizations.id = monitors.organization_id
 AND organizations.deleted_at IS NULL
JOIN org_members
  ON org_members.organization_id = monitors.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE monitors.environment_id = $2::text::uuid
  AND monitors.id = $3::text::uuid
  AND monitors.deleted_at IS NULL
`

type AuthorizeBackendMonitorParams struct {
	UserID        string
	EnvironmentID string
	MonitorID     string
}

type AuthorizeBackendMonitorRow struct {
	OrganizationID string
	Role           string
}

func (q *Queries) AuthorizeBackendMonitor(ctx context.Context, arg AuthorizeBackendMonitorParams) (AuthorizeBackendMonitorRow, error) {
	row := q.db.QueryRow(ctx, authorizeBackendMonitor, arg.UserID, arg.EnvironmentID, arg.MonitorID)
	var i AuthorizeBackendMonitorRow
	err := row.Scan(&i.OrganizationID, &i.Role)
	return i, err
}

const countOpenEnvironmentIncidents = `-- name: CountOpenEnvironmentIncidents :one
SELECT count(*)
FROM incidents
WHERE environment_id = $1::text::uuid
  AND status = 'open'
`

func (q *Queries) CountOpenEnvironmentIncidents(ctx context.Context, environmentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenEnvironmentIncidents, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnvironmentMonitorStateCounts = `-- name: GetEnvironmentMonitorStateCounts :one
SELECT
    count(*) FILTER (WHERE COALESCE(states.display_state, 'unknown') = 'healthy') AS healthy,
    count(*) FILTER (WHERE COALESCE(states.display_state, 'unknown') = 'degraded') AS degraded,
    count(*) FILTER (WHERE COALESCE(states.display_state, 'unknown') = 'down') AS down,
    count(*) FILTER (WHERE COALESCE(states.display_state, 'unknown') = 'unknown') AS unknown
FROM monitors
LEFT JOIN monitor_reliability_states AS states ON states.monitor_id = monitors.id
WHERE monitors.environment_id = $1::text::uuid
  AND monitors.deleted_at IS NULL
`

type GetEnvironmentMonitorStateCountsRow struct {
	Healthy  int64
	Degraded int64
	Down     int64
	Unknown  int64
}

func (q *Queries) GetEnvironmentMonitorStateCounts(ctx context.Context, environmentID string) (GetEnvironmentMonitorStateCountsRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentMonitorStateCounts, environmentID)
	var i GetEnvironmentMonitorStateCountsRow
	err := row.Scan(
		&i.Healthy,
		&i.Degraded,
		&i.Down,
		&i.Unknown,
	)
	return i, err
}

const getEnvironmentReliability = `-- name: GetEnvironmentReliability :one
WITH expected AS (
    SELECT periods.monitor_id, slot
    FROM monitor_schedule_periods AS periods
    CROSS JOIN LATERAL generate_series(
        periods.first_slot_at
          + GREATEST(
              0,
              ceil(EXTRACT(EPOCH FROM ($1 - periods.first_slot_at))
                   / periods.interval_seconds)::bigint
            ) * make_interval(secs => periods.interval_seconds),
        LEAST(COALESCE(periods.ends_at, $2), $2)
          - INTERVAL '1 microsecond',
        make_interval(secs => periods.interval_seconds)
    ) AS slot
    WHERE periods.environment_id = $3::text::uuid
      AND periods.starts_at < $2
      AND COALESCE(periods.ends_at, $2) > $1
      AND slot >= GREATEST($1, periods.starts_at)
), aggregate AS (
    SELECT count(*)::bigint AS expected,
           count(health_checks.job_id)::bigint AS observed,
           count(health_checks.job_id) FILTER (WHERE health_checks.succeeded)::bigint AS successful,
           count(health_checks.job_id)::bigint AS latency_samples,
           COALESCE(sum(health_checks.total_duration_microseconds), 0)::bigint AS latency_total_us
    FROM expected
    LEFT JOIN health_checks
      ON health_checks.monitor_id = expected.monitor_id
     AND health_checks.job_type = 'scheduled'
     AND health_checks.scheduled_at = expected.slot
)
SELECT expected, observed, successful, latency_samples, latency_total_us
FROM aggregate
`

type GetEnvironmentReliabilityParams struct {
	FromAt        pgtype.Timestamptz
	ToAt          pgtype.Timestamptz
	EnvironmentID string
}

type GetEnvironmentReliabilityRow struct {
	Expected       int64
	Observed       int64
	Successful     int64
	LatencySamples int64
	LatencyTotalUs int64
}

func (q *Queries) GetEnvironmentReliability(ctx context.Context, arg GetEnvironmentReliabilityParams) (GetEnvironmentReliabilityRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentReliability, arg.FromAt, arg.ToAt, arg.EnvironmentID)
	var i GetEnvironmentReliabilityRow
	err := row.Scan(
		&i.Expected,
		&i.Observed,
		&i.Successful,
		&i.LatencySamples,
		&i.LatencyTotalUs,
	)
	return i, err
}

const getFirstEnvironmentRollupInvalidation = `-- name: GetFirstEnvironmentRollupInvalidation :one
SELECT invalidations.invalidated_at
FROM monitor_rollup_invalidations AS invalidations
JOIN monitors ON monitors.id = invalidations.monitor_id
WHERE monitors.environment_id = $1::text::uuid
  AND invalidations.bucket_start < $2
  AND invalidations.bucket_start + CASE invalidations.bucket_kind
        WHEN 'hourly' THEN INTERVAL '1 hour'
        ELSE INTERVAL '1 day'
      END > $3
ORDER BY invalidations.invalidated_at
LIMIT 1
`

type GetFirstEnvironmentRollupInvalidationParams struct {
	EnvironmentID string
	ToAt          pgtype.Timestamptz
	FromAt        pgtype.Timestamptz
}

func (q *Queries) GetFirstEnvironmentRollupInvalidation(ctx context.Context, arg GetFirstEnvironmentRollupInvalidationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFirstEnvironmentRollupInvalidation, arg.EnvironmentID, arg.ToAt, arg.FromAt)
	var invalidated_at pgtype.Timestamptz
	err := row.Scan(&invalidated_at)
	return invalidated_at, err
}

const getFirstMonitorRollupInvalidation = `-- name: GetFirstMonitorRollupInvalidation :one
SELECT invalidated_at
FROM monitor_rollup_invalidations
WHERE monitor_id = $1::text::uuid
  AND bucket_start < $2
  AND bucket_start + CASE bucket_kind
        WHEN 'hourly' THEN INTERVAL '1 hour'
        ELSE INTERVAL '1 day'
      END > $3
ORDER BY invalidated_at
LIMIT 1
`

type GetFirstMonitorRollupInvalidationParams struct {
	MonitorID string
	ToAt      pgtype.Timestamptz
	FromAt    pgtype.Timestamptz
}

func (q *Queries) GetFirstMonitorRollupInvalidation(ctx context.Context, arg GetFirstMonitorRollupInvalidationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFirstMonitorRollupInvalidation, arg.MonitorID, arg.ToAt, arg.FromAt)
	var invalidated_at pgtype.Timestamptz
	err := row.Scan(&invalidated_at)
	return invalidated_at, err
}

const getMonitorLatencyTotals = `-- name: GetMonitorLatencyTotals :one
SELECT count(*) AS sample_count,
       COALESCE(sum(total_duration_microseconds), 0)::bigint AS total_duration_us
FROM health_checks
WHERE monitor_id = $1::text::uuid
  AND job_type = 'scheduled'
  AND scheduled_at >= $2
  AND scheduled_at < $3
`

type GetMonitorLatencyTotalsParams struct {
	MonitorID string
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
}

type GetMonitorLatencyTotalsRow struct {
	SampleCount     int64
	TotalDurationUs int64
}

func (q *Queries) GetMonitorLatencyTotals(ctx context.Context, arg GetMonitorLatencyTotalsParams) (GetMonitorLatencyTotalsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorLatencyTotals, arg.MonitorID, arg.FromAt, arg.ToAt)
	var i GetMonitorLatencyTotalsRow
	err := row.Scan(&i.SampleCount, &i.TotalDurationUs)
	return i, err
}

const listBackendChecks = `-- name: ListBackendChecks :many
SELECT job_id::text AS job_id, job_type, scheduled_at, started_at,
       completed_at, succeeded, status_code, error_category,
       total_duration_microseconds
FROM health_checks
WHERE monitor_id = $1::text::uuid
  AND scheduled_at >= $2
  AND scheduled_at < $3
  AND ($4::text = '' OR job_type = $4)
  AND (
      NOT $5::boolean
      OR (scheduled_at, job_id) < (
          $6, $7::text::uuid
      )
  )
ORDER BY scheduled_at DESC, job_id DESC
LIMIT $8
`

type ListBackendChecksParams struct {
	MonitorID   string
	FromAt      pgtype.Timestamptz
	ToAt        pgtype.Timestamptz
	JobType     string
	HasCursor   bool
	CursorAt    pgtype.Timestamptz
	CursorID    string
	ResultLimit int32
}

type ListBackendChecksRow struct {
	JobID                     string
	JobType                   string
	ScheduledAt               pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	CompletedAt               pgtype.Timestamptz
	Succeeded                 bool
	StatusCode                pgtype.Int2
	ErrorCategory             pgtype.Text
	TotalDurationMicroseconds int64
}

func (q *Queries) ListBackendChecks(ctx context.Context, arg ListBackendChecksParams) ([]ListBackendChecksRow, error) {
	rows, err := q.db.Query(ctx, listBackendChecks,
		arg.MonitorID,
		arg.FromAt,
		arg.ToAt,
		arg.JobType,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendChecksRow{}
	for rows.Next() {
		var i ListBackendChecksRow
		if err := rows.Scan(
			&i.JobID,
			&i.JobType,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Succeeded,
			&i.StatusCode,
			&i.ErrorCategory,
			&i.TotalDurationMicroseconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackendIncidentEvents = `-- name: ListBackendIncidentEvents :many
SELECT id::text AS id, event_type,
       actor_user_id, source_job_id,
       safe_reason, occurred_at
FROM incident_events
WHERE incident_id = $1::text::uuid
ORDER BY occurred_at, id
LIMIT 200
`

type ListBackendIncidentEventsRow struct {
	ID          string
	EventType   string
	ActorUserID pgtype.UUID
	SourceJobID pgtype.UUID
	SafeReason  pgtype.Text
	OccurredAt  pgtype.Timestamptz
}

func (q *Queries) ListBackendIncidentEvents(ctx context.Context, incidentID string) ([]ListBackendIncidentEventsRow, error) {
	rows, err := q.db.Query(ctx, listBackendIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendIncidentEventsRow{}
	for rows.Next() {
		var i ListBackendIncidentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorUserID,
			&i.SourceJobID,
			&i.SafeReason,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackendIncidents = `-- name: ListBackendIncidents :many
SELECT id::text AS id, organization_id::text AS organization_id,
       environment_id::text AS environment_id, monitor_id::text AS monitor_id,
       status, started_at, opened_at, acknowledged_at,
       acknowledged_by_user_id, resolved_at, resolved_by_user_id,
       resolution_kind, resolution_reason
FROM incidents
WHERE environment_id = $1::text::uuid
  AND opened_at >= $2
  AND opened_at < $3
  AND ($4::text = '' OR status = $4)
  AND (
      NOT $5::boolean
      OR (opened_at, id) < (
          $6, $7::text::uuid
      )
  )
ORDER BY opened_at DESC, id DESC
LIMIT $8
`

type ListBackendIncidentsParams struct {
	EnvironmentID string
	FromAt        pgtype.Timestamptz
	ToAt          pgtype.Timestamptz
	Status        string
	HasCursor     bool
	CursorAt      pgtype.Timestamptz
	CursorID      string
	ResultLimit   int32
}

type ListBackendIncidentsRow struct {
	ID                   string
	OrganizationID       string
	EnvironmentID        string
	MonitorID            string
	Status               string
	StartedAt            pgtype.Timestamptz
	OpenedAt             pgtype.Timestamptz
	AcknowledgedAt       pgtype.Timestamptz
	AcknowledgedByUserID pgtype.UUID
	ResolvedAt           pgtype.Timestamptz
	ResolvedByUserID     pgtype.UUID
	ResolutionKind       pgtype.Text
	ResolutionReason     pgtype.Text
}

func (q *Queries) ListBackendIncidents(ctx context.Context, arg ListBackendIncidentsParams) ([]ListBackendIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listBackendIncidents,
		arg.EnvironmentID,
		arg.FromAt,
		arg.ToAt,
		arg.Status,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendIncidentsRow{}
	for rows.Next() {
		var i ListBackendIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EnvironmentID,
			&i.MonitorID,
			&i.Status,
			&i.StartedAt,
			&i.OpenedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ResolvedAt,
			&i.ResolvedByUserID,
			&i.ResolutionKind,
			&i.ResolutionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackendNotificationDeliveries = `-- name: ListBackendNotificationDeliveries :many
SELECT delivery_id::text AS delivery_id, transition, state, attempt_count,
       next_attempt_at, last_provider_status, accepted_at, failed_at
FROM notification_outbox
WHERE incident_id = $1::text::uuid
ORDER BY created_at, delivery_id
LIMIT 200
`

type ListBackendNotificationDeliveriesRow struct {
	DeliveryID         string
	Transition         string
	State              string
	AttemptCount       int16
	NextAttemptAt      pgtype.Timestamptz
	LastProviderStatus pgtype.Text
	AcceptedAt         pgtype.Timestamptz
	FailedAt           pgtype.Timestamptz
}

func (q *Queries) ListBackendNotificationDeliveries(ctx context.Context, incidentID string) ([]ListBackendNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listBackendNotificationDeliveries, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendNotificationDeliveriesRow{}
	for rows.Next() {
		var i ListBackendNotificationDeliveriesRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Transition,
			&i.State,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastProviderStatus,
			&i.AcceptedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
