// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checker.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingCheckJob = `-- name: ClaimPendingCheckJob :one
WITH candidate AS (
    SELECT check_jobs.id
    FROM check_jobs
    WHERE check_jobs.state = 'pending'
      AND check_jobs.attempt_count < check_jobs.max_attempts
    ORDER BY
        CASE check_jobs.job_type WHEN 'scheduled' THEN 0 ELSE 1 END,
        check_jobs.scheduled_at,
        check_jobs.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE check_jobs
SET state = 'running',
    attempt_count = check_jobs.attempt_count + 1,
    lease_owner = $1,
    lease_token = gen_random_uuid(),
    lease_expires_at = CURRENT_TIMESTAMP + $2::integer * INTERVAL '1 second',
    started_at = COALESCE(check_jobs.started_at, CURRENT_TIMESTAMP),
    completed_at = NULL
FROM candidate, monitors
WHERE check_jobs.id = candidate.id
  AND monitors.organization_id = check_jobs.organization_id
  AND monitors.environment_id = check_jobs.environment_id
  AND monitors.id = check_jobs.monitor_id
RETURNING
    check_jobs.id::text AS job_id,
    check_jobs.organization_id::text AS organization_id,
    check_jobs.environment_id::text AS environment_id,
    check_jobs.monitor_id::text AS monitor_id,
    check_jobs.job_type,
    check_jobs.scheduled_at,
    check_jobs.started_at,
    check_jobs.lease_token::text AS lease_token,
    check_jobs.lease_expires_at,
    check_jobs.attempt_count,
    monitors.target_url,
    monitors.method,
    monitors.timeout_seconds,
    monitors.expected_status_min,
    monitors.expected_status_max
`

type ClaimPendingCheckJobParams struct {
	LeaseOwner   pgtype.Text
	LeaseSeconds int32
}

type ClaimPendingCheckJobRow struct {
	JobID             string
	OrganizationID    string
	EnvironmentID     string
	MonitorID         string
	JobType           string
	ScheduledAt       pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	LeaseToken        string
	LeaseExpiresAt    pgtype.Timestamptz
	AttemptCount      int16
	TargetUrl         string
	Method            string
	TimeoutSeconds    int32
	ExpectedStatusMin int16
	ExpectedStatusMax int16
}

func (q *Queries) ClaimPendingCheckJob(ctx context.Context, arg ClaimPendingCheckJobParams) (ClaimPendingCheckJobRow, error) {
	row := q.db.QueryRow(ctx, claimPendingCheckJob, arg.LeaseOwner, arg.LeaseSeconds)
	var i ClaimPendingCheckJobRow
	err := row.Scan(
		&i.JobID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.MonitorID,
		&i.JobType,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.AttemptCount,
		&i.TargetUrl,
		&i.Method,
		&i.TimeoutSeconds,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
	)
	return i, err
}

const completeCheckJob = `-- name: CompleteCheckJob :execrows
UPDATE check_jobs
SET state = 'completed',
    completed_at = $1,
    lease_owner = NULL,
    lease_token = NULL,
    lease_expires_at = NULL
WHERE id = $2::text::uuid
  AND organization_id = $3::text::uuid
  AND environment_id = $4::text::uuid
  AND monitor_id = $5::text::uuid
  AND state = 'running'
  AND lease_token = $6::text::uuid
`

type CompleteCheckJobParams struct {
	CompletedAt    pgtype.Timestamptz
	JobID          string
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	LeaseToken     string
}

func (q *Queries) CompleteCheckJob(ctx context.Context, arg CompleteCheckJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCheckJob,
		arg.CompletedAt,
		arg.JobID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const healthCheckExists = `-- name: HealthCheckExists :one
SELECT EXISTS (
    SELECT 1
    FROM health_checks
    WHERE job_id = $1::text::uuid
      AND organization_id = $2::text::uuid
      AND environment_id = $3::text::uuid
      AND monitor_id = $4::text::uuid
) AS result_exists
`

type HealthCheckExistsParams struct {
	JobID          string
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
}

func (q *Queries) HealthCheckExists(ctx context.Context, arg HealthCheckExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, healthCheckExists,
		arg.JobID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
	)
	var result_exists bool
	err := row.Scan(&result_exists)
	return result_exists, err
}

const insertHealthCheck = `-- name: InsertHealthCheck :execrows
INSERT INTO health_checks (
    job_id,
    organization_id,
    environment_id,
    monitor_id,
    job_type,
    scheduled_at,
    started_at,
    completed_at,
    succeeded,
    status_code,
    error_category,
    total_duration_microseconds
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4::text::uuid,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (job_id) DO NOTHING
`

type InsertHealthCheckParams struct {
	JobID                     string
	OrganizationID            string
	EnvironmentID             string
	MonitorID                 string
	JobType                   string
	ScheduledAt               pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	CompletedAt               pgtype.Timestamptz
	Succeeded                 bool
	StatusCode                pgtype.Int2
	ErrorCategory             pgtype.Text
	TotalDurationMicroseconds int64
}

func (q *Queries) InsertHealthCheck(ctx context.Context, arg InsertHealthCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertHealthCheck,
		arg.JobID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.JobType,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Succeeded,
		arg.StatusCode,
		arg.ErrorCategory,
		arg.TotalDurationMicroseconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockCheckJobForCompletion = `-- name: LockCheckJobForCompletion :one
SELECT
    check_jobs.id::text AS job_id,
    check_jobs.organization_id::text AS organization_id,
    check_jobs.environment_id::text AS environment_id,
    check_jobs.monitor_id::text AS monitor_id,
    check_jobs.job_type,
    check_jobs.state,
    check_jobs.scheduled_at,
    COALESCE(
        lease_token,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::text AS lease_token
FROM check_jobs
JOIN monitors
  ON monitors.organization_id = check_jobs.organization_id
 AND monitors.environment_id = check_jobs.environment_id
 AND monitors.id = check_jobs.monitor_id
WHERE check_jobs.id = $1::text::uuid
  AND check_jobs.organization_id = $2::text::uuid
  AND check_jobs.environment_id = $3::text::uuid
  AND check_jobs.monitor_id = $4::text::uuid
FOR UPDATE OF check_jobs
`

type LockCheckJobForCompletionParams struct {
	JobID          string
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
}

type LockCheckJobForCompletionRow struct {
	JobID          string
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	JobType        string
	State          string
	ScheduledAt    pgtype.Timestamptz
	LeaseToken     string
}

func (q *Queries) LockCheckJobForCompletion(ctx context.Context, arg LockCheckJobForCompletionParams) (LockCheckJobForCompletionRow, error) {
	row := q.db.QueryRow(ctx, lockCheckJobForCompletion,
		arg.JobID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
	)
	var i LockCheckJobForCompletionRow
	err := row.Scan(
		&i.JobID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.MonitorID,
		&i.JobType,
		&i.State,
		&i.ScheduledAt,
		&i.LeaseToken,
	)
	return i, err
}
