// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fifo.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDispatchOutbox = `-- name: ClaimDispatchOutbox :one
WITH candidate AS (
    SELECT job_id
    FROM check_dispatch_outbox
    WHERE publish_state = 'pending'
      AND publish_attempts < 3
      AND next_attempt_at <= CURRENT_TIMESTAMP
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE check_dispatch_outbox AS outbox
SET publish_state = 'publishing',
    publish_attempts = publish_attempts + 1,
    publish_lease_token = gen_random_uuid(),
    publish_lease_expires_at = CURRENT_TIMESTAMP + INTERVAL '45 seconds',
    updated_at = CURRENT_TIMESTAMP
FROM candidate
WHERE outbox.job_id = candidate.job_id
RETURNING outbox.job_id::text AS job_id,
          outbox.worker_pool_id,
          outbox.queue_url,
          outbox.message_body,
          outbox.snapshot_hash,
          outbox.message_deduplication_id,
          outbox.message_group_id,
          outbox.expires_at,
          outbox.publish_attempts,
          outbox.schema_version,
          outbox.platform_key_id,
          outbox.worker_encryption_key_id,
          outbox.publish_lease_token::text AS publish_lease_token
`

type ClaimDispatchOutboxRow struct {
	JobID                  string
	WorkerPoolID           string
	QueueUrl               string
	MessageBody            []byte
	SnapshotHash           []byte
	MessageDeduplicationID string
	MessageGroupID         string
	ExpiresAt              pgtype.Timestamptz
	PublishAttempts        int16
	SchemaVersion          int16
	PlatformKeyID          string
	WorkerEncryptionKeyID  string
	PublishLeaseToken      string
}

func (q *Queries) ClaimDispatchOutbox(ctx context.Context) (ClaimDispatchOutboxRow, error) {
	row := q.db.QueryRow(ctx, claimDispatchOutbox)
	var i ClaimDispatchOutboxRow
	err := row.Scan(
		&i.JobID,
		&i.WorkerPoolID,
		&i.QueueUrl,
		&i.MessageBody,
		&i.SnapshotHash,
		&i.MessageDeduplicationID,
		&i.MessageGroupID,
		&i.ExpiresAt,
		&i.PublishAttempts,
		&i.SchemaVersion,
		&i.PlatformKeyID,
		&i.WorkerEncryptionKeyID,
		&i.PublishLeaseToken,
	)
	return i, err
}

const completeCheckJob = `-- name: CompleteCheckJob :exec
UPDATE check_jobs
SET state = 'completed',
    started_at = $1,
    completed_at = $2,
    worker_id = $3,
    execution_attempt_id = $4::text::uuid,
    last_safe_error = NULL
WHERE id = $5::text::uuid
`

type CompleteCheckJobParams struct {
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	WorkerID           pgtype.Text
	ExecutionAttemptID string
	JobID              string
}

func (q *Queries) CompleteCheckJob(ctx context.Context, arg CompleteCheckJobParams) error {
	_, err := q.db.Exec(ctx, completeCheckJob,
		arg.StartedAt,
		arg.CompletedAt,
		arg.WorkerID,
		arg.ExecutionAttemptID,
		arg.JobID,
	)
	return err
}

const countActiveScheduledJobs = `-- name: CountActiveScheduledJobs :one
SELECT count(*)
FROM check_jobs
WHERE job_type = 'scheduled'
  AND state IN ('pending', 'pending_publish', 'published', 'running')
`

func (q *Queries) CountActiveScheduledJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveScheduledJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduledCheckJob = `-- name: CreateScheduledCheckJob :execrows
INSERT INTO check_jobs (
    id, organization_id, environment_id, monitor_id, job_type, state,
    scheduled_at, monitor_version, worker_pool_id, snapshot_hash, expires_at
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4::text::uuid,
    'scheduled',
    'pending_publish',
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (monitor_id, scheduled_at) DO NOTHING
`

type CreateScheduledCheckJobParams struct {
	JobID          string
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	ScheduledAt    pgtype.Timestamptz
	MonitorVersion int64
	WorkerPoolID   string
	SnapshotHash   []byte
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateScheduledCheckJob(ctx context.Context, arg CreateScheduledCheckJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, createScheduledCheckJob,
		arg.JobID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.ScheduledAt,
		arg.MonitorVersion,
		arg.WorkerPoolID,
		arg.SnapshotHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createScheduledDispatchOutbox = `-- name: CreateScheduledDispatchOutbox :exec
INSERT INTO check_dispatch_outbox (
    job_id, worker_pool_id, queue_url, message_body, schema_version,
    platform_key_id, worker_encryption_key_id, snapshot_hash,
    message_deduplication_id, message_group_id, expires_at
)
VALUES (
    $1::text::uuid,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $1,
    $1,
    $9
)
`

type CreateScheduledDispatchOutboxParams struct {
	JobID                 string
	WorkerPoolID          string
	QueueUrl              string
	MessageBody           []byte
	SchemaVersion         int16
	PlatformKeyID         string
	WorkerEncryptionKeyID string
	SnapshotHash          []byte
	ExpiresAt             pgtype.Timestamptz
}

func (q *Queries) CreateScheduledDispatchOutbox(ctx context.Context, arg CreateScheduledDispatchOutboxParams) error {
	_, err := q.db.Exec(ctx, createScheduledDispatchOutbox,
		arg.JobID,
		arg.WorkerPoolID,
		arg.QueueUrl,
		arg.MessageBody,
		arg.SchemaVersion,
		arg.PlatformKeyID,
		arg.WorkerEncryptionKeyID,
		arg.SnapshotHash,
		arg.ExpiresAt,
	)
	return err
}

const databasePing = `-- name: DatabasePing :one
SELECT 1::integer AS ready
`

func (q *Queries) DatabasePing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, databasePing)
	var ready int32
	err := row.Scan(&ready)
	return ready, err
}

const deleteOldLedgerJobs = `-- name: DeleteOldLedgerJobs :execrows
DELETE FROM check_jobs
WHERE (state = 'completed' AND completed_at < $1)
   OR (state IN ('dead', 'expired', 'cancelled', 'quarantined')
       AND completed_at < $2)
`

type DeleteOldLedgerJobsParams struct {
	CompletedBefore   pgtype.Timestamptz
	NonterminalBefore pgtype.Timestamptz
}

func (q *Queries) DeleteOldLedgerJobs(ctx context.Context, arg DeleteOldLedgerJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldLedgerJobs, arg.CompletedBefore, arg.NonterminalBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveredCoverageGaps = `-- name: DeleteRecoveredCoverageGaps :exec
DELETE FROM monitoring_coverage_gaps
WHERE monitor_id = $1::text::uuid
  AND scheduled_at = $2
  AND reason IN ('expired', 'dead')
`

type DeleteRecoveredCoverageGapsParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) DeleteRecoveredCoverageGaps(ctx context.Context, arg DeleteRecoveredCoverageGapsParams) error {
	_, err := q.db.Exec(ctx, deleteRecoveredCoverageGaps, arg.MonitorID, arg.ScheduledAt)
	return err
}

const expireClaimedDispatch = `-- name: ExpireClaimedDispatch :exec
UPDATE check_dispatch_outbox
SET publish_state = 'expired',
    publish_lease_token = NULL,
    publish_lease_expires_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE job_id = $1::text::uuid
  AND publish_lease_token = $2::text::uuid
`

type ExpireClaimedDispatchParams struct {
	JobID      string
	LeaseToken string
}

func (q *Queries) ExpireClaimedDispatch(ctx context.Context, arg ExpireClaimedDispatchParams) error {
	_, err := q.db.Exec(ctx, expireClaimedDispatch, arg.JobID, arg.LeaseToken)
	return err
}

const expireUnpublishedCheckJob = `-- name: ExpireUnpublishedCheckJob :exec
UPDATE check_jobs
SET state = 'expired',
    completed_at = CURRENT_TIMESTAMP,
    last_safe_error = 'dispatch_expired'
WHERE id = $1::text::uuid
  AND state IN ('pending', 'pending_publish')
`

func (q *Queries) ExpireUnpublishedCheckJob(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, expireUnpublishedCheckJob, jobID)
	return err
}

const getAcceptedHealthCheck = `-- name: GetAcceptedHealthCheck :one
SELECT snapshot_hash, execution_attempt_id::text AS execution_attempt_id,
       result_id::text AS result_id
FROM health_checks
WHERE job_id = $1::text::uuid
`

type GetAcceptedHealthCheckRow struct {
	SnapshotHash       []byte
	ExecutionAttemptID string
	ResultID           string
}

func (q *Queries) GetAcceptedHealthCheck(ctx context.Context, jobID string) (GetAcceptedHealthCheckRow, error) {
	row := q.db.QueryRow(ctx, getAcceptedHealthCheck, jobID)
	var i GetAcceptedHealthCheckRow
	err := row.Scan(&i.SnapshotHash, &i.ExecutionAttemptID, &i.ResultID)
	return i, err
}

const getCheckJobStateCounts = `-- name: GetCheckJobStateCounts :one
SELECT count(*) FILTER (WHERE state IN ('pending', 'pending_publish')) AS pending,
       count(*) FILTER (WHERE state = 'published') AS published,
       count(*) FILTER (WHERE state = 'running') AS running,
       count(*) FILTER (WHERE state = 'dead') AS dead,
       count(*) FILTER (WHERE state = 'expired') AS expired
FROM check_jobs
`

type GetCheckJobStateCountsRow struct {
	Pending   int64
	Published int64
	Running   int64
	Dead      int64
	Expired   int64
}

func (q *Queries) GetCheckJobStateCounts(ctx context.Context) (GetCheckJobStateCountsRow, error) {
	row := q.db.QueryRow(ctx, getCheckJobStateCounts)
	var i GetCheckJobStateCountsRow
	err := row.Scan(
		&i.Pending,
		&i.Published,
		&i.Running,
		&i.Dead,
		&i.Expired,
	)
	return i, err
}

const getDispatchStateCounts = `-- name: GetDispatchStateCounts :one
SELECT count(*) FILTER (WHERE publish_state IN ('pending', 'publishing')) AS pending,
       count(*) FILTER (WHERE publish_state = 'ambiguous') AS ambiguous
FROM check_dispatch_outbox
`

type GetDispatchStateCountsRow struct {
	Pending   int64
	Ambiguous int64
}

func (q *Queries) GetDispatchStateCounts(ctx context.Context) (GetDispatchStateCountsRow, error) {
	row := q.db.QueryRow(ctx, getDispatchStateCounts)
	var i GetDispatchStateCountsRow
	err := row.Scan(&i.Pending, &i.Ambiguous)
	return i, err
}

const getOldestActiveCheckJob = `-- name: GetOldestActiveCheckJob :one
SELECT created_at
FROM check_jobs
WHERE state IN ('pending', 'pending_publish', 'published', 'running')
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetOldestActiveCheckJob(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getOldestActiveCheckJob)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getOldestNonterminalDispatch = `-- name: GetOldestNonterminalDispatch :one
SELECT created_at
FROM check_dispatch_outbox
WHERE publish_state IN ('pending', 'publishing', 'ambiguous')
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetOldestNonterminalDispatch(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getOldestNonterminalDispatch)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertAcceptedCheckRefreshEvent = `-- name: InsertAcceptedCheckRefreshEvent :exec
INSERT INTO api_refresh_events (
    organization_id, environment_id, event_type, resource_type, resource_id
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    'check.accepted',
    'check',
    $3::text::uuid
)
`

type InsertAcceptedCheckRefreshEventParams struct {
	OrganizationID string
	EnvironmentID  string
	JobID          string
}

func (q *Queries) InsertAcceptedCheckRefreshEvent(ctx context.Context, arg InsertAcceptedCheckRefreshEventParams) error {
	_, err := q.db.Exec(ctx, insertAcceptedCheckRefreshEvent, arg.OrganizationID, arg.EnvironmentID, arg.JobID)
	return err
}

const insertAcceptedHealthCheck = `-- name: InsertAcceptedHealthCheck :exec
INSERT INTO health_checks (
    job_id, result_id, organization_id, environment_id, monitor_id, job_type,
    scheduled_at, started_at, completed_at, succeeded, status_code,
    error_category, total_duration_microseconds, snapshot_hash, worker_pool_id,
    worker_id, execution_attempt_id, dns_duration_microseconds,
    connect_duration_microseconds, tls_duration_microseconds,
    first_byte_duration_microseconds
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4::text::uuid,
    $5::text::uuid,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17::text::uuid,
    $18,
    $19,
    $20,
    $21
)
`

type InsertAcceptedHealthCheckParams struct {
	JobID                         string
	ResultID                      string
	OrganizationID                string
	EnvironmentID                 string
	MonitorID                     string
	JobType                       string
	ScheduledAt                   pgtype.Timestamptz
	StartedAt                     pgtype.Timestamptz
	CompletedAt                   pgtype.Timestamptz
	Succeeded                     bool
	StatusCode                    pgtype.Int2
	ErrorCategory                 pgtype.Text
	TotalDurationMicroseconds     int64
	SnapshotHash                  []byte
	WorkerPoolID                  pgtype.Text
	WorkerID                      pgtype.Text
	ExecutionAttemptID            string
	DnsDurationMicroseconds       pgtype.Int8
	ConnectDurationMicroseconds   pgtype.Int8
	TlsDurationMicroseconds       pgtype.Int8
	FirstByteDurationMicroseconds pgtype.Int8
}

func (q *Queries) InsertAcceptedHealthCheck(ctx context.Context, arg InsertAcceptedHealthCheckParams) error {
	_, err := q.db.Exec(ctx, insertAcceptedHealthCheck,
		arg.JobID,
		arg.ResultID,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.JobType,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Succeeded,
		arg.StatusCode,
		arg.ErrorCategory,
		arg.TotalDurationMicroseconds,
		arg.SnapshotHash,
		arg.WorkerPoolID,
		arg.WorkerID,
		arg.ExecutionAttemptID,
		arg.DnsDurationMicroseconds,
		arg.ConnectDurationMicroseconds,
		arg.TlsDurationMicroseconds,
		arg.FirstByteDurationMicroseconds,
	)
	return err
}

const insertConflictingResultQuarantine = `-- name: InsertConflictingResultQuarantine :exec
INSERT INTO monitoring_quarantine (
    queue_kind, job_id, result_id, worker_pool_id, snapshot_hash,
    safe_reason, encrypted_payload
)
VALUES (
    'result',
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    'conflicting valid result',
    $5
)
`

type InsertConflictingResultQuarantineParams struct {
	JobID            string
	ResultID         string
	WorkerPoolID     pgtype.Text
	SnapshotHash     []byte
	EncryptedPayload []byte
}

func (q *Queries) InsertConflictingResultQuarantine(ctx context.Context, arg InsertConflictingResultQuarantineParams) error {
	_, err := q.db.Exec(ctx, insertConflictingResultQuarantine,
		arg.JobID,
		arg.ResultID,
		arg.WorkerPoolID,
		arg.SnapshotHash,
		arg.EncryptedPayload,
	)
	return err
}

const insertDeadCoverageGapFromJob = `-- name: InsertDeadCoverageGapFromJob :exec
INSERT INTO monitoring_coverage_gaps (
    organization_id, environment_id, monitor_id, scheduled_at, reason
)
SELECT organization_id, environment_id, monitor_id, scheduled_at, 'dead'
FROM check_jobs
WHERE id = $1::text::uuid
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertDeadCoverageGapFromJob(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, insertDeadCoverageGapFromJob, jobID)
	return err
}

const insertExpiredCoverageGapFromJob = `-- name: InsertExpiredCoverageGapFromJob :exec
INSERT INTO monitoring_coverage_gaps (
    organization_id, environment_id, monitor_id, scheduled_at, reason
)
SELECT organization_id, environment_id, monitor_id, scheduled_at, 'expired'
FROM check_jobs
WHERE id = $1::text::uuid
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertExpiredCoverageGapFromJob(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, insertExpiredCoverageGapFromJob, jobID)
	return err
}

const insertInvalidResultQuarantine = `-- name: InsertInvalidResultQuarantine :exec
INSERT INTO monitoring_quarantine (queue_kind, safe_reason, encrypted_payload)
VALUES ('result', 'invalid result DLQ envelope', $1)
`

func (q *Queries) InsertInvalidResultQuarantine(ctx context.Context, encryptedPayload []byte) error {
	_, err := q.db.Exec(ctx, insertInvalidResultQuarantine, encryptedPayload)
	return err
}

const insertMonitoringCoverageGap = `-- name: InsertMonitoringCoverageGap :exec
INSERT INTO monitoring_coverage_gaps (
    organization_id, environment_id, monitor_id, scheduled_at, reason
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4,
    $5
)
ON CONFLICT DO NOTHING
`

type InsertMonitoringCoverageGapParams struct {
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	ScheduledAt    pgtype.Timestamptz
	Reason         string
}

func (q *Queries) InsertMonitoringCoverageGap(ctx context.Context, arg InsertMonitoringCoverageGapParams) error {
	_, err := q.db.Exec(ctx, insertMonitoringCoverageGap,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.ScheduledAt,
		arg.Reason,
	)
	return err
}

const insertMonitoringOperationalEvent = `-- name: InsertMonitoringOperationalEvent :exec
INSERT INTO monitoring_operational_events (
    event_type, job_id, worker_pool_id, safe_details
)
VALUES (
    $1,
    NULLIF($2::text, '')::uuid,
    NULLIF($3::text, ''),
    $4
)
`

type InsertMonitoringOperationalEventParams struct {
	EventType    string
	JobID        string
	WorkerPoolID string
	SafeDetails  string
}

func (q *Queries) InsertMonitoringOperationalEvent(ctx context.Context, arg InsertMonitoringOperationalEventParams) error {
	_, err := q.db.Exec(ctx, insertMonitoringOperationalEvent,
		arg.EventType,
		arg.JobID,
		arg.WorkerPoolID,
		arg.SafeDetails,
	)
	return err
}

const insertResultConflict = `-- name: InsertResultConflict :exec
INSERT INTO check_result_conflicts (
    job_id, result_id, worker_pool_id, snapshot_hash, safe_reason, encrypted_payload
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    'conflicting valid result',
    $5
)
ON CONFLICT (result_id) DO NOTHING
`

type InsertResultConflictParams struct {
	JobID            string
	ResultID         string
	WorkerPoolID     string
	SnapshotHash     []byte
	EncryptedPayload []byte
}

func (q *Queries) InsertResultConflict(ctx context.Context, arg InsertResultConflictParams) error {
	_, err := q.db.Exec(ctx, insertResultConflict,
		arg.JobID,
		arg.ResultID,
		arg.WorkerPoolID,
		arg.SnapshotHash,
		arg.EncryptedPayload,
	)
	return err
}

const insertResultDLQQuarantine = `-- name: InsertResultDLQQuarantine :exec
INSERT INTO monitoring_quarantine (
    queue_kind, job_id, result_id, worker_pool_id, snapshot_hash,
    safe_reason, encrypted_payload
)
VALUES (
    'result',
    $1::text::uuid,
    $2::text::uuid,
    $3,
    decode($4, 'hex'),
    'result DLQ recovery',
    $5
)
ON CONFLICT DO NOTHING
`

type InsertResultDLQQuarantineParams struct {
	JobID            string
	ResultID         string
	WorkerPoolID     pgtype.Text
	SnapshotHash     string
	EncryptedPayload []byte
}

func (q *Queries) InsertResultDLQQuarantine(ctx context.Context, arg InsertResultDLQQuarantineParams) error {
	_, err := q.db.Exec(ctx, insertResultDLQQuarantine,
		arg.JobID,
		arg.ResultID,
		arg.WorkerPoolID,
		arg.SnapshotHash,
		arg.EncryptedPayload,
	)
	return err
}

const listDueScheduledMonitors = `-- name: ListDueScheduledMonitors :many
SELECT monitors.id::text AS id,
       monitors.organization_id::text AS organization_id,
       monitors.environment_id::text AS environment_id,
       monitors.version,
       monitors.target_url,
       monitors.method,
       monitors.interval_seconds,
       monitors.timeout_seconds,
       monitors.expected_status_min,
       monitors.expected_status_max,
       monitors.next_check_at,
       monitors.headers_ciphertext,
       monitors.header_key_version,
       monitors.worker_pool_id,
       worker_pools.network_policy_version,
       worker_pools.encryption_key_id,
       worker_pools.encryption_public_key,
       worker_pools.job_queue_url,
       worker_pools.schema_min,
       worker_pools.schema_max
FROM monitors
JOIN worker_pools
  ON worker_pools.id = monitors.worker_pool_id
 AND worker_pools.enabled
 AND worker_pools.lifecycle_state = 'active'
WHERE monitors.next_check_at <= CURRENT_TIMESTAMP
  AND monitors.paused_at IS NULL
  AND monitors.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM check_jobs
      WHERE check_jobs.monitor_id = monitors.id
        AND check_jobs.job_type = 'scheduled'
        AND check_jobs.state IN ('pending', 'pending_publish', 'published', 'running')
  )
ORDER BY monitors.next_check_at, monitors.id
LIMIT $1
FOR UPDATE OF monitors SKIP LOCKED
`

type ListDueScheduledMonitorsRow struct {
	ID                   string
	OrganizationID       string
	EnvironmentID        string
	Version              int64
	TargetUrl            string
	Method               string
	IntervalSeconds      int32
	TimeoutSeconds       int32
	ExpectedStatusMin    int16
	ExpectedStatusMax    int16
	NextCheckAt          pgtype.Timestamptz
	HeadersCiphertext    []byte
	HeaderKeyVersion     pgtype.Int4
	WorkerPoolID         string
	NetworkPolicyVersion int32
	EncryptionKeyID      pgtype.Text
	EncryptionPublicKey  []byte
	JobQueueUrl          pgtype.Text
	SchemaMin            int16
	SchemaMax            int16
}

func (q *Queries) ListDueScheduledMonitors(ctx context.Context, batchSize int32) ([]ListDueScheduledMonitorsRow, error) {
	rows, err := q.db.Query(ctx, listDueScheduledMonitors, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueScheduledMonitorsRow{}
	for rows.Next() {
		var i ListDueScheduledMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EnvironmentID,
			&i.Version,
			&i.TargetUrl,
			&i.Method,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.ExpectedStatusMin,
			&i.ExpectedStatusMax,
			&i.NextCheckAt,
			&i.HeadersCiphertext,
			&i.HeaderKeyVersion,
			&i.WorkerPoolID,
			&i.NetworkPolicyVersion,
			&i.EncryptionKeyID,
			&i.EncryptionPublicKey,
			&i.JobQueueUrl,
			&i.SchemaMin,
			&i.SchemaMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResultCheckJob = `-- name: LockResultCheckJob :one
SELECT check_jobs.worker_pool_id,
       check_jobs.snapshot_hash,
       COALESCE(
           (
               SELECT worker_pool_credentials.public_material
               FROM worker_pool_credentials
               WHERE worker_pool_credentials.worker_pool_id = check_jobs.worker_pool_id
                 AND worker_pool_credentials.purpose = 'result_signing'
                 AND worker_pool_credentials.key_id = $1
                 AND worker_pool_credentials.status IN ('active', 'retired')
               ORDER BY worker_pool_credentials.activates_at DESC
               LIMIT 1
           ),
           CASE
             WHEN worker_pools.result_key_id = $1
             THEN worker_pools.result_public_key
           END
       )::bytea AS result_public_key,
       check_jobs.state,
       check_jobs.job_type,
       check_jobs.organization_id::text AS organization_id,
       check_jobs.environment_id::text AS environment_id,
       check_jobs.monitor_id::text AS monitor_id,
       check_jobs.scheduled_at,
       check_jobs.expires_at
FROM check_jobs
JOIN worker_pools ON worker_pools.id = check_jobs.worker_pool_id
WHERE check_jobs.id = $2::text::uuid
FOR UPDATE OF check_jobs
`

type LockResultCheckJobParams struct {
	ResultKeyID string
	JobID       string
}

type LockResultCheckJobRow struct {
	WorkerPoolID    string
	SnapshotHash    []byte
	ResultPublicKey []byte
	State           string
	JobType         string
	OrganizationID  string
	EnvironmentID   string
	MonitorID       string
	ScheduledAt     pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) LockResultCheckJob(ctx context.Context, arg LockResultCheckJobParams) (LockResultCheckJobRow, error) {
	row := q.db.QueryRow(ctx, lockResultCheckJob, arg.ResultKeyID, arg.JobID)
	var i LockResultCheckJobRow
	err := row.Scan(
		&i.WorkerPoolID,
		&i.SnapshotHash,
		&i.ResultPublicKey,
		&i.State,
		&i.JobType,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.MonitorID,
		&i.ScheduledAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markCheckJobDead = `-- name: MarkCheckJobDead :execrows
UPDATE check_jobs
SET state = 'dead', completed_at = CURRENT_TIMESTAMP, last_safe_error = 'job_dlq'
WHERE id = $1::text::uuid
  AND worker_pool_id = $2
  AND state <> 'completed'
`

type MarkCheckJobDeadParams struct {
	JobID        string
	WorkerPoolID string
}

func (q *Queries) MarkCheckJobDead(ctx context.Context, arg MarkCheckJobDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCheckJobDead, arg.JobID, arg.WorkerPoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCheckJobPublished = `-- name: MarkCheckJobPublished :exec
UPDATE check_jobs
SET state = 'published', sqs_message_id = $1
WHERE id = $2::text::uuid
  AND state IN ('pending', 'pending_publish')
`

type MarkCheckJobPublishedParams struct {
	MessageID pgtype.Text
	JobID     string
}

func (q *Queries) MarkCheckJobPublished(ctx context.Context, arg MarkCheckJobPublishedParams) error {
	_, err := q.db.Exec(ctx, markCheckJobPublished, arg.MessageID, arg.JobID)
	return err
}

const markDispatchPublishFailure = `-- name: MarkDispatchPublishFailure :exec
UPDATE check_dispatch_outbox
SET publish_state = $1,
    next_attempt_at = CURRENT_TIMESTAMP
      + $2::integer * INTERVAL '1 second',
    publish_lease_token = NULL,
    publish_lease_expires_at = NULL,
    last_safe_error = 'sqs_send_failed',
    updated_at = CURRENT_TIMESTAMP
WHERE job_id = $3::text::uuid
  AND publish_lease_token = $4::text::uuid
`

type MarkDispatchPublishFailureParams struct {
	PublishState string
	DelaySeconds int32
	JobID        string
	LeaseToken   string
}

func (q *Queries) MarkDispatchPublishFailure(ctx context.Context, arg MarkDispatchPublishFailureParams) error {
	_, err := q.db.Exec(ctx, markDispatchPublishFailure,
		arg.PublishState,
		arg.DelaySeconds,
		arg.JobID,
		arg.LeaseToken,
	)
	return err
}

const markDispatchPublished = `-- name: MarkDispatchPublished :exec
UPDATE check_dispatch_outbox
SET publish_state = 'published',
    sqs_message_id = $1,
    published_at = CURRENT_TIMESTAMP,
    publish_lease_token = NULL,
    publish_lease_expires_at = NULL,
    last_safe_error = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE job_id = $2::text::uuid
  AND publish_lease_token = $3::text::uuid
`

type MarkDispatchPublishedParams struct {
	MessageID  pgtype.Text
	JobID      string
	LeaseToken string
}

func (q *Queries) MarkDispatchPublished(ctx context.Context, arg MarkDispatchPublishedParams) error {
	_, err := q.db.Exec(ctx, markDispatchPublished, arg.MessageID, arg.JobID, arg.LeaseToken)
	return err
}

const markDispatchRepaired = `-- name: MarkDispatchRepaired :exec
UPDATE check_dispatch_outbox
SET publish_state = 'repaired', updated_at = CURRENT_TIMESTAMP
WHERE job_id = $1::text::uuid
  AND publish_state <> 'published'
`

func (q *Queries) MarkDispatchRepaired(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, markDispatchRepaired, jobID)
	return err
}

const newScheduledJobID = `-- name: NewScheduledJobID :one
SELECT gen_random_uuid()::text AS job_id
`

func (q *Queries) NewScheduledJobID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, newScheduledJobID)
	var job_id string
	err := row.Scan(&job_id)
	return job_id, err
}

const reclaimDispatchPublisherLeases = `-- name: ReclaimDispatchPublisherLeases :execrows
UPDATE check_dispatch_outbox
SET publish_state = CASE
      WHEN publish_attempts >= 3 THEN 'ambiguous'
      ELSE 'pending'
    END,
    publish_lease_token = NULL,
    publish_lease_expires_at = NULL,
    last_safe_error = 'publisher_interrupted',
    updated_at = CURRENT_TIMESTAMP
WHERE publish_state = 'publishing'
  AND publish_lease_expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) ReclaimDispatchPublisherLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimDispatchPublisherLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpiredCheckJobs = `-- name: SweepExpiredCheckJobs :execrows
WITH expired AS (
    UPDATE check_jobs
    SET state = 'expired',
        completed_at = CURRENT_TIMESTAMP,
        last_safe_error = 'start_expired'
    WHERE state IN ('pending', 'pending_publish', 'published', 'running')
      AND expires_at < CURRENT_TIMESTAMP
      AND NOT EXISTS (
          SELECT 1 FROM health_checks WHERE health_checks.job_id = check_jobs.id
      )
    RETURNING organization_id, environment_id, monitor_id, scheduled_at
)
INSERT INTO monitoring_coverage_gaps (
    organization_id, environment_id, monitor_id, scheduled_at, reason
)
SELECT organization_id, environment_id, monitor_id, scheduled_at, 'expired'
FROM expired
ON CONFLICT DO NOTHING
`

func (q *Queries) SweepExpiredCheckJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredCheckJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMonitorNextCheck = `-- name: UpdateMonitorNextCheck :exec
UPDATE monitors
SET next_check_at = $1
WHERE id = $2::text::uuid
  AND next_check_at = $3
`

type UpdateMonitorNextCheckParams struct {
	NextCheckAt     pgtype.Timestamptz
	MonitorID       string
	PreviousCheckAt pgtype.Timestamptz
}

func (q *Queries) UpdateMonitorNextCheck(ctx context.Context, arg UpdateMonitorNextCheckParams) error {
	_, err := q.db.Exec(ctx, updateMonitorNextCheck, arg.NextCheckAt, arg.MonitorID, arg.PreviousCheckAt)
	return err
}

const upsertDailyRollupInvalidation = `-- name: UpsertDailyRollupInvalidation :exec
INSERT INTO monitor_rollup_invalidations (
    monitor_id, bucket_kind, bucket_start, reason
)
VALUES (
    $1::text::uuid,
    'daily',
    date_trunc('day', $2::timestamptz AT TIME ZONE 'UTC') AT TIME ZONE 'UTC',
    $3
)
ON CONFLICT (monitor_id, bucket_kind, bucket_start)
DO UPDATE SET reason = EXCLUDED.reason, invalidated_at = CURRENT_TIMESTAMP
`

type UpsertDailyRollupInvalidationParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	Reason      string
}

func (q *Queries) UpsertDailyRollupInvalidation(ctx context.Context, arg UpsertDailyRollupInvalidationParams) error {
	_, err := q.db.Exec(ctx, upsertDailyRollupInvalidation, arg.MonitorID, arg.ScheduledAt, arg.Reason)
	return err
}

const upsertHourlyRollupInvalidation = `-- name: UpsertHourlyRollupInvalidation :exec
INSERT INTO monitor_rollup_invalidations (
    monitor_id, bucket_kind, bucket_start, reason
)
VALUES (
    $1::text::uuid,
    'hourly',
    date_trunc('hour', $2::timestamptz AT TIME ZONE 'UTC') AT TIME ZONE 'UTC',
    $3
)
ON CONFLICT (monitor_id, bucket_kind, bucket_start)
DO UPDATE SET reason = EXCLUDED.reason, invalidated_at = CURRENT_TIMESTAMP
`

type UpsertHourlyRollupInvalidationParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	Reason      string
}

func (q *Queries) UpsertHourlyRollupInvalidation(ctx context.Context, arg UpsertHourlyRollupInvalidationParams) error {
	_, err := q.db.Exec(ctx, upsertHourlyRollupInvalidation, arg.MonitorID, arg.ScheduledAt, arg.Reason)
	return err
}
