// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeOpenIncident = `-- name: AcknowledgeOpenIncident :exec
UPDATE incidents
SET acknowledged_at = $1,
    acknowledged_by_user_id = $2::text::uuid,
    updated_at = $1
WHERE id = $3::text::uuid
  AND status = 'open'
  AND acknowledged_at IS NULL
`

type AcknowledgeOpenIncidentParams struct {
	AcknowledgedAt pgtype.Timestamptz
	UserID         string
	IncidentID     string
}

func (q *Queries) AcknowledgeOpenIncident(ctx context.Context, arg AcknowledgeOpenIncidentParams) error {
	_, err := q.db.Exec(ctx, acknowledgeOpenIncident, arg.AcknowledgedAt, arg.UserID, arg.IncidentID)
	return err
}

const createOpenIncident = `-- name: CreateOpenIncident :one
INSERT INTO incidents (
    organization_id, environment_id, monitor_id, alert_rule_id,
    started_at, opened_at
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4::text::uuid,
    $5,
    $6
)
ON CONFLICT (monitor_id, alert_rule_id) WHERE status = 'open' DO NOTHING
RETURNING id::text AS id
`

type CreateOpenIncidentParams struct {
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	RuleID         string
	StartedAt      pgtype.Timestamptz
	OpenedAt       pgtype.Timestamptz
}

func (q *Queries) CreateOpenIncident(ctx context.Context, arg CreateOpenIncidentParams) (string, error) {
	row := q.db.QueryRow(ctx, createOpenIncident,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.RuleID,
		arg.StartedAt,
		arg.OpenedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureDefaultAlertRule = `-- name: EnsureDefaultAlertRule :exec
INSERT INTO alert_rules (organization_id, environment_id, monitor_id)
SELECT organization_id, environment_id, id
FROM monitors
WHERE id = $1::text::uuid
ON CONFLICT (monitor_id, rule_key) DO NOTHING
`

func (q *Queries) EnsureDefaultAlertRule(ctx context.Context, monitorID string) error {
	_, err := q.db.Exec(ctx, ensureDefaultAlertRule, monitorID)
	return err
}

const getEnabledMonitorAlertRule = `-- name: GetEnabledMonitorAlertRule :one
SELECT alert_rules.id::text AS rule_id,
       alert_rules.organization_id::text AS organization_id,
       alert_rules.environment_id::text AS environment_id,
       alert_rules.failure_threshold,
       monitor_reliability_states.observed_state
FROM alert_rules
JOIN monitor_reliability_states
  ON monitor_reliability_states.monitor_id = alert_rules.monitor_id
WHERE alert_rules.monitor_id = $1::text::uuid
  AND alert_rules.rule_key = 'consecutive_failures'
  AND alert_rules.enabled
`

type GetEnabledMonitorAlertRuleRow struct {
	RuleID           string
	OrganizationID   string
	EnvironmentID    string
	FailureThreshold int16
	ObservedState    string
}

func (q *Queries) GetEnabledMonitorAlertRule(ctx context.Context, monitorID string) (GetEnabledMonitorAlertRuleRow, error) {
	row := q.db.QueryRow(ctx, getEnabledMonitorAlertRule, monitorID)
	var i GetEnabledMonitorAlertRuleRow
	err := row.Scan(
		&i.RuleID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.FailureThreshold,
		&i.ObservedState,
	)
	return i, err
}

const getIncidentTenant = `-- name: GetIncidentTenant :one
SELECT organization_id::text AS organization_id,
       environment_id::text AS environment_id
FROM incidents
WHERE id = $1::text::uuid
`

type GetIncidentTenantRow struct {
	OrganizationID string
	EnvironmentID  string
}

func (q *Queries) GetIncidentTenant(ctx context.Context, incidentID string) (GetIncidentTenantRow, error) {
	row := q.db.QueryRow(ctx, getIncidentTenant, incidentID)
	var i GetIncidentTenantRow
	err := row.Scan(&i.OrganizationID, &i.EnvironmentID)
	return i, err
}

const insertIncidentRefreshEvent = `-- name: InsertIncidentRefreshEvent :exec
INSERT INTO api_refresh_events (
    organization_id, environment_id, event_type, resource_type, resource_id
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    'incident.changed',
    'incident',
    $3::text::uuid
)
`

type InsertIncidentRefreshEventParams struct {
	OrganizationID string
	EnvironmentID  string
	IncidentID     string
}

func (q *Queries) InsertIncidentRefreshEvent(ctx context.Context, arg InsertIncidentRefreshEventParams) error {
	_, err := q.db.Exec(ctx, insertIncidentRefreshEvent, arg.OrganizationID, arg.EnvironmentID, arg.IncidentID)
	return err
}

const listRecentIncidentEvaluationTimes = `-- name: ListRecentIncidentEvaluationTimes :many
SELECT scheduled_at
FROM monitor_result_evaluations
WHERE monitor_id = $1::text::uuid
ORDER BY scheduled_at DESC, job_id DESC
LIMIT $2
`

type ListRecentIncidentEvaluationTimesParams struct {
	MonitorID        string
	FailureThreshold int32
}

func (q *Queries) ListRecentIncidentEvaluationTimes(ctx context.Context, arg ListRecentIncidentEvaluationTimesParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listRecentIncidentEvaluationTimes, arg.MonitorID, arg.FailureThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Timestamptz{}
	for rows.Next() {
		var scheduled_at pgtype.Timestamptz
		if err := rows.Scan(&scheduled_at); err != nil {
			return nil, err
		}
		items = append(items, scheduled_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAuthorizedIncident = `-- name: LoadAuthorizedIncident :one
SELECT incidents.id::text AS id,
       incidents.organization_id::text AS organization_id,
       incidents.environment_id::text AS environment_id,
       incidents.monitor_id::text AS monitor_id,
       incidents.status,
       incidents.started_at,
       incidents.opened_at,
       incidents.acknowledged_at,
       incidents.acknowledged_by_user_id,
       incidents.resolved_at,
       incidents.resolved_by_user_id,
       incidents.resolution_kind,
       incidents.resolution_reason,
       org_members.role
FROM incidents
JOIN org_members
  ON org_members.organization_id = incidents.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE incidents.environment_id = $2::text::uuid
  AND incidents.id = $3::text::uuid
FOR UPDATE OF incidents
`

type LoadAuthorizedIncidentParams struct {
	UserID        string
	EnvironmentID string
	IncidentID    string
}

type LoadAuthorizedIncidentRow struct {
	ID                   string
	OrganizationID       string
	EnvironmentID        string
	MonitorID            string
	Status               string
	StartedAt            pgtype.Timestamptz
	OpenedAt             pgtype.Timestamptz
	AcknowledgedAt       pgtype.Timestamptz
	AcknowledgedByUserID pgtype.UUID
	ResolvedAt           pgtype.Timestamptz
	ResolvedByUserID     pgtype.UUID
	ResolutionKind       pgtype.Text
	ResolutionReason     pgtype.Text
	Role                 string
}

func (q *Queries) LoadAuthorizedIncident(ctx context.Context, arg LoadAuthorizedIncidentParams) (LoadAuthorizedIncidentRow, error) {
	row := q.db.QueryRow(ctx, loadAuthorizedIncident, arg.UserID, arg.EnvironmentID, arg.IncidentID)
	var i LoadAuthorizedIncidentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.MonitorID,
		&i.Status,
		&i.StartedAt,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.ResolutionKind,
		&i.ResolutionReason,
		&i.Role,
	)
	return i, err
}

const lockOpenIncident = `-- name: LockOpenIncident :one
SELECT id::text AS id
FROM incidents
WHERE monitor_id = $1::text::uuid
  AND alert_rule_id = $2::text::uuid
  AND status = 'open'
FOR UPDATE
`

type LockOpenIncidentParams struct {
	MonitorID string
	RuleID    string
}

func (q *Queries) LockOpenIncident(ctx context.Context, arg LockOpenIncidentParams) (string, error) {
	row := q.db.QueryRow(ctx, lockOpenIncident, arg.MonitorID, arg.RuleID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveOpenIncident = `-- name: ResolveOpenIncident :execrows
UPDATE incidents
SET status = 'resolved',
    resolved_at = $1,
    resolved_by_user_id = NULLIF($2::text, '')::uuid,
    resolution_kind = $3,
    resolution_reason = NULLIF(btrim($4::text), ''),
    updated_at = $1
WHERE id = $5::text::uuid
  AND status = 'open'
`

type ResolveOpenIncidentParams struct {
	ResolvedAt       pgtype.Timestamptz
	ActorUserID      string
	ResolutionKind   pgtype.Text
	ResolutionReason string
	IncidentID       string
}

func (q *Queries) ResolveOpenIncident(ctx context.Context, arg ResolveOpenIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveOpenIncident,
		arg.ResolvedAt,
		arg.ActorUserID,
		arg.ResolutionKind,
		arg.ResolutionReason,
		arg.IncidentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIncidentEvent = `-- name: UpsertIncidentEvent :one
INSERT INTO incident_events (
    organization_id, environment_id, incident_id, event_key, event_type,
    actor_user_id, source_job_id, safe_reason, occurred_at
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4,
    $5,
    NULLIF($6::text, '')::uuid,
    NULLIF($7::text, '')::uuid,
    NULLIF(btrim($8::text), ''),
    $9
)
ON CONFLICT (incident_id, event_key)
DO UPDATE SET event_key = EXCLUDED.event_key
RETURNING id::text AS id
`

type UpsertIncidentEventParams struct {
	OrganizationID string
	EnvironmentID  string
	IncidentID     string
	EventKey       string
	EventType      string
	ActorUserID    string
	SourceJobID    string
	SafeReason     string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) UpsertIncidentEvent(ctx context.Context, arg UpsertIncidentEventParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertIncidentEvent,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.IncidentID,
		arg.EventKey,
		arg.EventType,
		arg.ActorUserID,
		arg.SourceJobID,
		arg.SafeReason,
		arg.OccurredAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
