// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationMonitors = `-- name: CountOrganizationMonitors :one
SELECT count(*) AS monitor_count
FROM monitors
WHERE organization_id = $1::text::uuid
`

func (q *Queries) CountOrganizationMonitors(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMonitors, organizationID)
	var monitor_count int64
	err := row.Scan(&monitor_count)
	return monitor_count, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    organization_id,
    environment_id,
    name,
    target_url,
    interval_seconds,
    timeout_seconds,
    expected_status_min,
    expected_status_max
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id::text AS id,
    organization_id::text AS organization_id,
    environment_id::text AS environment_id,
    name,
    target_url,
    method,
    interval_seconds,
    timeout_seconds,
    expected_status_min,
    expected_status_max,
    created_at,
    updated_at
`

type CreateMonitorParams struct {
	OrganizationID    string
	EnvironmentID     string
	Name              string
	TargetUrl         string
	IntervalSeconds   int32
	TimeoutSeconds    int32
	ExpectedStatusMin int16
	ExpectedStatusMax int16
}

type CreateMonitorRow struct {
	ID                string
	OrganizationID    string
	EnvironmentID     string
	Name              string
	TargetUrl         string
	Method            string
	IntervalSeconds   int32
	TimeoutSeconds    int32
	ExpectedStatusMin int16
	ExpectedStatusMax int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (CreateMonitorRow, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.Name,
		arg.TargetUrl,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.ExpectedStatusMin,
		arg.ExpectedStatusMax,
	)
	var i CreateMonitorRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.Name,
		&i.TargetUrl,
		&i.Method,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessibleEnvironmentOrganization = `-- name: GetAccessibleEnvironmentOrganization :one
SELECT environments.organization_id::text AS organization_id
FROM environments
JOIN organizations ON organizations.id = environments.organization_id
JOIN org_members
  ON org_members.organization_id = environments.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE environments.id = $2::text::uuid
  AND organizations.deleted_at IS NULL
`

type GetAccessibleEnvironmentOrganizationParams struct {
	UserID        string
	EnvironmentID string
}

func (q *Queries) GetAccessibleEnvironmentOrganization(ctx context.Context, arg GetAccessibleEnvironmentOrganizationParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccessibleEnvironmentOrganization, arg.UserID, arg.EnvironmentID)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const listEnvironmentMonitors = `-- name: ListEnvironmentMonitors :many
SELECT
    id::text AS id,
    organization_id::text AS organization_id,
    environment_id::text AS environment_id,
    name,
    target_url,
    method,
    interval_seconds,
    timeout_seconds,
    expected_status_min,
    expected_status_max,
    created_at,
    updated_at
FROM monitors
WHERE organization_id = $1::text::uuid
  AND environment_id = $2::text::uuid
ORDER BY created_at, id
`

type ListEnvironmentMonitorsParams struct {
	OrganizationID string
	EnvironmentID  string
}

type ListEnvironmentMonitorsRow struct {
	ID                string
	OrganizationID    string
	EnvironmentID     string
	Name              string
	TargetUrl         string
	Method            string
	IntervalSeconds   int32
	TimeoutSeconds    int32
	ExpectedStatusMin int16
	ExpectedStatusMax int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListEnvironmentMonitors(ctx context.Context, arg ListEnvironmentMonitorsParams) ([]ListEnvironmentMonitorsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentMonitors, arg.OrganizationID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentMonitorsRow{}
	for rows.Next() {
		var i ListEnvironmentMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EnvironmentID,
			&i.Name,
			&i.TargetUrl,
			&i.Method,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.ExpectedStatusMin,
			&i.ExpectedStatusMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironmentForMonitorCreation = `-- name: LockEnvironmentForMonitorCreation :one
SELECT environments.organization_id::text AS organization_id
FROM environments
JOIN organizations ON organizations.id = environments.organization_id
JOIN org_members
  ON org_members.organization_id = environments.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE environments.id = $2::text::uuid
  AND organizations.deleted_at IS NULL
  AND org_members.role IN ('owner', 'admin', 'member')
FOR UPDATE OF organizations
`

type LockEnvironmentForMonitorCreationParams struct {
	UserID        string
	EnvironmentID string
}

func (q *Queries) LockEnvironmentForMonitorCreation(ctx context.Context, arg LockEnvironmentForMonitorCreationParams) (string, error) {
	row := q.db.QueryRow(ctx, lockEnvironmentForMonitorCreation, arg.UserID, arg.EnvironmentID)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}
