// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptNotificationDelivery = `-- name: AcceptNotificationDelivery :execrows
UPDATE notification_outbox
SET state = 'accepted',
    attempt_count = $1,
    provider_message_id = $2,
    last_provider_status = $3,
    accepted_at = $4,
    lease_owner = NULL,
    lease_token = NULL,
    lease_expires_at = NULL,
    updated_at = $4
WHERE delivery_id = $5::text::uuid
  AND state = 'leased'
  AND lease_token = $6::text::uuid
`

type AcceptNotificationDeliveryParams struct {
	AttemptNumber     int16
	ProviderMessageID pgtype.Text
	ProviderStatus    pgtype.Text
	AttemptedAt       pgtype.Timestamptz
	DeliveryID        string
	LeaseToken        string
}

func (q *Queries) AcceptNotificationDelivery(ctx context.Context, arg AcceptNotificationDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptNotificationDelivery,
		arg.AttemptNumber,
		arg.ProviderMessageID,
		arg.ProviderStatus,
		arg.AttemptedAt,
		arg.DeliveryID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNotificationDelivery = `-- name: ClaimNotificationDelivery :one
WITH candidate AS (
    SELECT delivery_id
    FROM notification_outbox
    WHERE state = 'pending'
      AND next_attempt_at <= $3
      AND attempt_count < 4
    ORDER BY next_attempt_at, created_at, delivery_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE notification_outbox AS outbox
SET state = 'leased',
    lease_owner = $1,
    lease_token = gen_random_uuid(),
    lease_expires_at = $2,
    updated_at = $3
FROM candidate
WHERE outbox.delivery_id = candidate.delivery_id
RETURNING outbox.delivery_id::text AS delivery_id,
          outbox.incident_id::text AS incident_id,
          outbox.organization_id::text AS organization_id,
          (SELECT environment_id::text FROM incidents WHERE id = outbox.incident_id) AS environment_id,
          outbox.recipient_email,
          outbox.transition,
          outbox.lease_token::text AS lease_token,
          outbox.attempt_count + 1 AS attempt_number
`

type ClaimNotificationDeliveryParams struct {
	WorkerID       pgtype.Text
	LeaseExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
}

type ClaimNotificationDeliveryRow struct {
	DeliveryID     string
	IncidentID     string
	OrganizationID string
	EnvironmentID  string
	RecipientEmail string
	Transition     string
	LeaseToken     string
	AttemptNumber  int32
}

func (q *Queries) ClaimNotificationDelivery(ctx context.Context, arg ClaimNotificationDeliveryParams) (ClaimNotificationDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimNotificationDelivery, arg.WorkerID, arg.LeaseExpiresAt, arg.ClaimedAt)
	var i ClaimNotificationDeliveryRow
	err := row.Scan(
		&i.DeliveryID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.EnvironmentID,
		&i.RecipientEmail,
		&i.Transition,
		&i.LeaseToken,
		&i.AttemptNumber,
	)
	return i, err
}

const completeFailedNotificationAttempt = `-- name: CompleteFailedNotificationAttempt :execrows
UPDATE notification_outbox
SET state = $1,
    attempt_count = $2,
    next_attempt_at = $3,
    last_provider_status = $4,
    failed_at = CASE
      WHEN $1::text = 'failed' THEN $5::timestamptz
      ELSE NULL
    END,
    lease_owner = NULL,
    lease_token = NULL,
    lease_expires_at = NULL,
    updated_at = $5
WHERE delivery_id = $6::text::uuid
  AND state = 'leased'
  AND lease_token = $7::text::uuid
`

type CompleteFailedNotificationAttemptParams struct {
	State          string
	AttemptNumber  int16
	NextAttemptAt  pgtype.Timestamptz
	ProviderStatus pgtype.Text
	AttemptedAt    pgtype.Timestamptz
	DeliveryID     string
	LeaseToken     string
}

func (q *Queries) CompleteFailedNotificationAttempt(ctx context.Context, arg CompleteFailedNotificationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeFailedNotificationAttempt,
		arg.State,
		arg.AttemptNumber,
		arg.NextAttemptAt,
		arg.ProviderStatus,
		arg.AttemptedAt,
		arg.DeliveryID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueIncidentNotifications = `-- name: EnqueueIncidentNotifications :execrows
INSERT INTO notification_outbox (
    organization_id, incident_id, incident_event_id, recipient_user_id,
    recipient_email, transition
)
SELECT incident_events.organization_id,
       incident_events.incident_id,
       incident_events.id,
       org_members.user_id,
       lower(btrim(users.email)),
       $1
FROM incident_events
JOIN org_members ON org_members.organization_id = incident_events.organization_id
JOIN users ON users.id = org_members.user_id
WHERE incident_events.id = $2::text::uuid
  AND users.email_verified_at IS NOT NULL
  AND org_members.incident_notifications_enabled
  AND org_members.role IN ('owner', 'admin', 'member', 'viewer')
ON CONFLICT (incident_event_id, recipient_user_id, channel) DO NOTHING
`

type EnqueueIncidentNotificationsParams struct {
	Transition string
	EventID    string
}

func (q *Queries) EnqueueIncidentNotifications(ctx context.Context, arg EnqueueIncidentNotificationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueIncidentNotifications, arg.Transition, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationAttempt = `-- name: InsertNotificationAttempt :exec
INSERT INTO notification_attempts (
    delivery_id, attempt_number, outcome, provider_status, attempted_at
)
VALUES (
    $1::text::uuid,
    $2,
    $3,
    $4,
    $5
)
`

type InsertNotificationAttemptParams struct {
	DeliveryID     string
	AttemptNumber  int16
	Outcome        string
	ProviderStatus string
	AttemptedAt    pgtype.Timestamptz
}

func (q *Queries) InsertNotificationAttempt(ctx context.Context, arg InsertNotificationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertNotificationAttempt,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.Outcome,
		arg.ProviderStatus,
		arg.AttemptedAt,
	)
	return err
}

const insertNotificationRefreshEvent = `-- name: InsertNotificationRefreshEvent :exec
INSERT INTO api_refresh_events (
    organization_id, environment_id, event_type, resource_type, resource_id
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    'notification.changed',
    'notification',
    $3::text::uuid
)
`

type InsertNotificationRefreshEventParams struct {
	OrganizationID string
	EnvironmentID  string
	DeliveryID     string
}

func (q *Queries) InsertNotificationRefreshEvent(ctx context.Context, arg InsertNotificationRefreshEventParams) error {
	_, err := q.db.Exec(ctx, insertNotificationRefreshEvent, arg.OrganizationID, arg.EnvironmentID, arg.DeliveryID)
	return err
}

const reclaimExpiredNotificationLeases = `-- name: ReclaimExpiredNotificationLeases :execrows
UPDATE notification_outbox
SET state = 'pending',
    next_attempt_at = LEAST(next_attempt_at, $1),
    lease_owner = NULL,
    lease_token = NULL,
    lease_expires_at = NULL,
    updated_at = $1
WHERE state = 'leased'
  AND lease_expires_at <= $1
`

func (q *Queries) ReclaimExpiredNotificationLeases(ctx context.Context, reclaimedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimExpiredNotificationLeases, reclaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
