// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingNotifications = `-- name: CountPendingNotifications :one
SELECT count(*)::bigint
FROM notification_outbox
WHERE state IN ('pending','leased')
`

func (q *Queries) CountPendingNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingNotifications)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentCoverageGaps = `-- name: CountRecentCoverageGaps :one
SELECT count(*)::bigint
FROM monitoring_coverage_gaps
WHERE scheduled_at>CURRENT_TIMESTAMP-INTERVAL '24 hours'
`

func (q *Queries) CountRecentCoverageGaps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCoverageGaps)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpiredOrganizationInvitations = `-- name: DeleteExpiredOrganizationInvitations :execrows
DELETE FROM org_invitations
WHERE expires_at<($1::timestamptz-INTERVAL '7 days') OR accepted_at<($1::timestamptz-INTERVAL '7 days')
`

func (q *Queries) DeleteExpiredOrganizationInvitations(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOrganizationInvitations, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredUserActionTokens = `-- name: DeleteExpiredUserActionTokens :execrows
DELETE FROM user_action_tokens
WHERE expires_at<$1::timestamptz OR used_at<($1::timestamptz-INTERVAL '7 days')
`

func (q *Queries) DeleteExpiredUserActionTokens(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUserActionTokens, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldNotificationDeliveries = `-- name: DeleteOldNotificationDeliveries :execrows
DELETE FROM notification_outbox
WHERE state IN ('accepted','failed') AND updated_at<($1::timestamptz-INTERVAL '30 days')
`

func (q *Queries) DeleteOldNotificationDeliveries(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotificationDeliveries, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldRefreshEvents = `-- name: DeleteOldRefreshEvents :execrows
DELETE FROM api_refresh_events
WHERE occurred_at<($1::timestamptz-INTERVAL '1 day')
`

func (q *Queries) DeleteOldRefreshEvents(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRefreshEvents, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOldestPendingNotification = `-- name: GetOldestPendingNotification :one
SELECT created_at
FROM notification_outbox
WHERE state IN ('pending','leased')
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetOldestPendingNotification(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getOldestPendingNotification)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getRecentCheckCounts = `-- name: GetRecentCheckCounts :one
SELECT count(*)::bigint AS completed_checks,
       count(*) FILTER (WHERE NOT succeeded)::bigint AS failed_checks
FROM health_checks
WHERE completed_at>CURRENT_TIMESTAMP-INTERVAL '24 hours'
`

type GetRecentCheckCountsRow struct {
	CompletedChecks int64
	FailedChecks    int64
}

func (q *Queries) GetRecentCheckCounts(ctx context.Context) (GetRecentCheckCountsRow, error) {
	row := q.db.QueryRow(ctx, getRecentCheckCounts)
	var i GetRecentCheckCountsRow
	err := row.Scan(&i.CompletedChecks, &i.FailedChecks)
	return i, err
}

const getResultConsumerDelaySeconds = `-- name: GetResultConsumerDelaySeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-max(created_at)))::bigint,0)::bigint
FROM health_checks
`

func (q *Queries) GetResultConsumerDelaySeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getResultConsumerDelaySeconds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSchedulerDelaySeconds = `-- name: GetSchedulerDelaySeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-min(next_check_at)))::bigint,0)::bigint
FROM monitors
WHERE deleted_at IS NULL AND paused_at IS NULL AND next_check_at<CURRENT_TIMESTAMP
`

func (q *Queries) GetSchedulerDelaySeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSchedulerDelaySeconds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listMaintenanceStatuses = `-- name: ListMaintenanceStatuses :many
SELECT task_name,last_started_at,last_success_at,last_failure_at,last_safe_error,rows_affected
FROM maintenance_status
ORDER BY task_name
`

type ListMaintenanceStatusesRow struct {
	TaskName      string
	LastStartedAt pgtype.Timestamptz
	LastSuccessAt pgtype.Timestamptz
	LastFailureAt pgtype.Timestamptz
	LastSafeError pgtype.Text
	RowsAffected  int64
}

func (q *Queries) ListMaintenanceStatuses(ctx context.Context) ([]ListMaintenanceStatusesRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceStatusesRow{}
	for rows.Next() {
		var i ListMaintenanceStatusesRow
		if err := rows.Scan(
			&i.TaskName,
			&i.LastStartedAt,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.LastSafeError,
			&i.RowsAffected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceStatus = `-- name: UpdateMaintenanceStatus :execrows
UPDATE maintenance_status
SET last_started_at=$2,
    last_success_at=COALESCE($4,last_success_at),
    last_failure_at=COALESCE($5,last_failure_at),
    last_safe_error=$6,
    rows_affected=$3,
    updated_at=CURRENT_TIMESTAMP
WHERE task_name=$1
`

type UpdateMaintenanceStatusParams struct {
	TaskName      string
	LastStartedAt pgtype.Timestamptz
	RowsAffected  int64
	LastSuccessAt pgtype.Timestamptz
	LastFailureAt pgtype.Timestamptz
	LastSafeError pgtype.Text
}

func (q *Queries) UpdateMaintenanceStatus(ctx context.Context, arg UpdateMaintenanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMaintenanceStatus,
		arg.TaskName,
		arg.LastStartedAt,
		arg.RowsAffected,
		arg.LastSuccessAt,
		arg.LastFailureAt,
		arg.LastSafeError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
