// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package database

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id::text AS id, name, slug
`

type CreateOrganizationParams struct {
	Name string
	Slug string
}

type CreateOrganizationRow struct {
	ID   string
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i CreateOrganizationRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createOwnerMembership = `-- name: CreateOwnerMembership :exec
INSERT INTO org_members (organization_id, user_id, role)
VALUES ($1::text::uuid, $2::text::uuid, 'owner')
`

type CreateOwnerMembershipParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) CreateOwnerMembership(ctx context.Context, arg CreateOwnerMembershipParams) error {
	_, err := q.db.Exec(ctx, createOwnerMembership, arg.OrganizationID, arg.UserID)
	return err
}

const createProductionEnvironment = `-- name: CreateProductionEnvironment :one
INSERT INTO environments (organization_id, project_id, name, environment_type)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    'Production',
    'production'
)
RETURNING
    id::text AS id,
    organization_id::text AS organization_id,
    project_id::text AS project_id,
    name,
    environment_type
`

type CreateProductionEnvironmentParams struct {
	OrganizationID string
	ProjectID      string
}

type CreateProductionEnvironmentRow struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
}

func (q *Queries) CreateProductionEnvironment(ctx context.Context, arg CreateProductionEnvironmentParams) (CreateProductionEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createProductionEnvironment, arg.OrganizationID, arg.ProjectID)
	var i CreateProductionEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.EnvironmentType,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, name, description)
VALUES ($1::text::uuid, $2, $3)
RETURNING id::text AS id, organization_id::text AS organization_id, name, description
`

type CreateProjectParams struct {
	OrganizationID string
	Name           string
	Description    string
}

type CreateProjectRow struct {
	ID             string
	OrganizationID string
	Name           string
	Description    string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.Description)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
	)
	return i, err
}
