// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership_management.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeEnvironmentMembership = `-- name: AuthorizeEnvironmentMembership :one
SELECT environments.organization_id::text AS organization_id, org_members.role
FROM environments
JOIN organizations
  ON organizations.id = environments.organization_id
 AND organizations.deleted_at IS NULL
JOIN org_members
  ON org_members.organization_id = environments.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE environments.id = $2::text::uuid
`

type AuthorizeEnvironmentMembershipParams struct {
	UserID        string
	EnvironmentID string
}

type AuthorizeEnvironmentMembershipRow struct {
	OrganizationID string
	Role           string
}

func (q *Queries) AuthorizeEnvironmentMembership(ctx context.Context, arg AuthorizeEnvironmentMembershipParams) (AuthorizeEnvironmentMembershipRow, error) {
	row := q.db.QueryRow(ctx, authorizeEnvironmentMembership, arg.UserID, arg.EnvironmentID)
	var i AuthorizeEnvironmentMembershipRow
	err := row.Scan(&i.OrganizationID, &i.Role)
	return i, err
}

const authorizeProjectMembership = `-- name: AuthorizeProjectMembership :one
SELECT projects.organization_id::text AS organization_id, org_members.role
FROM projects
JOIN organizations
  ON organizations.id = projects.organization_id
 AND organizations.deleted_at IS NULL
JOIN org_members
  ON org_members.organization_id = projects.organization_id
 AND org_members.user_id = $1::text::uuid
WHERE projects.id = $2::text::uuid
`

type AuthorizeProjectMembershipParams struct {
	UserID    string
	ProjectID string
}

type AuthorizeProjectMembershipRow struct {
	OrganizationID string
	Role           string
}

func (q *Queries) AuthorizeProjectMembership(ctx context.Context, arg AuthorizeProjectMembershipParams) (AuthorizeProjectMembershipRow, error) {
	row := q.db.QueryRow(ctx, authorizeProjectMembership, arg.UserID, arg.ProjectID)
	var i AuthorizeProjectMembershipRow
	err := row.Scan(&i.OrganizationID, &i.Role)
	return i, err
}

const createTenantEnvironment = `-- name: CreateTenantEnvironment :one
INSERT INTO environments (organization_id, project_id, name, environment_type)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4
)
RETURNING id::text AS id, organization_id::text AS organization_id,
          project_id::text AS project_id, name, environment_type, created_at, updated_at
`

type CreateTenantEnvironmentParams struct {
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
}

type CreateTenantEnvironmentRow struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTenantEnvironment(ctx context.Context, arg CreateTenantEnvironmentParams) (CreateTenantEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createTenantEnvironment,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Name,
		arg.EnvironmentType,
	)
	var i CreateTenantEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.EnvironmentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantProject = `-- name: CreateTenantProject :one
INSERT INTO projects (organization_id, name, description)
VALUES (
    $1::text::uuid,
    $2,
    $3
)
RETURNING id::text AS id, organization_id::text AS organization_id, name,
          description, created_at, updated_at
`

type CreateTenantProjectParams struct {
	OrganizationID string
	Name           string
	Description    string
}

type CreateTenantProjectRow struct {
	ID             string
	OrganizationID string
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateTenantProject(ctx context.Context, arg CreateTenantProjectParams) (CreateTenantProjectRow, error) {
	row := q.db.QueryRow(ctx, createTenantProject, arg.OrganizationID, arg.Name, arg.Description)
	var i CreateTenantProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmptyTenantEnvironment = `-- name: DeleteEmptyTenantEnvironment :execrows
DELETE FROM environments
WHERE id = $1::text::uuid
  AND NOT EXISTS (
      SELECT 1 FROM monitors WHERE monitors.environment_id = environments.id
  )
`

func (q *Queries) DeleteEmptyTenantEnvironment(ctx context.Context, environmentID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyTenantEnvironment, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmptyTenantProject = `-- name: DeleteEmptyTenantProject :execrows
DELETE FROM projects
WHERE id = $1::text::uuid
  AND NOT EXISTS (
      SELECT 1 FROM environments WHERE environments.project_id = projects.id
  )
`

func (q *Queries) DeleteEmptyTenantProject(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyTenantProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM org_members
WHERE organization_id = $1::text::uuid
  AND user_id = $2::text::uuid
`

type DeleteOrganizationMemberParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const getAccessibleOrganization = `-- name: GetAccessibleOrganization :one
SELECT organizations.id::text AS id, organizations.name, organizations.slug,
       org_members.role, organizations.created_at
FROM organizations
JOIN org_members
  ON org_members.organization_id = organizations.id
 AND org_members.user_id = $1::text::uuid
WHERE organizations.id = $2::text::uuid
  AND organizations.deleted_at IS NULL
`

type GetAccessibleOrganizationParams struct {
	UserID         string
	OrganizationID string
}

type GetAccessibleOrganizationRow struct {
	ID        string
	Name      string
	Slug      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAccessibleOrganization(ctx context.Context, arg GetAccessibleOrganizationParams) (GetAccessibleOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getAccessibleOrganization, arg.UserID, arg.OrganizationID)
	var i GetAccessibleOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationMemberNotificationPreference = `-- name: GetOrganizationMemberNotificationPreference :one
SELECT incident_notifications_enabled
FROM org_members
WHERE organization_id = $1::text::uuid
  AND user_id = $2::text::uuid
`

type GetOrganizationMemberNotificationPreferenceParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) GetOrganizationMemberNotificationPreference(ctx context.Context, arg GetOrganizationMemberNotificationPreferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberNotificationPreference, arg.OrganizationID, arg.UserID)
	var incident_notifications_enabled bool
	err := row.Scan(&incident_notifications_enabled)
	return incident_notifications_enabled, err
}

const getOrganizationMemberRole = `-- name: GetOrganizationMemberRole :one
SELECT role
FROM org_members
WHERE organization_id = $1::text::uuid
  AND user_id = $2::text::uuid
`

type GetOrganizationMemberRoleParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) GetOrganizationMemberRole(ctx context.Context, arg GetOrganizationMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberRole, arg.OrganizationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTenantEnvironment = `-- name: GetTenantEnvironment :one
SELECT id::text AS id, organization_id::text AS organization_id,
       project_id::text AS project_id, name, environment_type, created_at, updated_at
FROM environments
WHERE id = $1::text::uuid
`

type GetTenantEnvironmentRow struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetTenantEnvironment(ctx context.Context, environmentID string) (GetTenantEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getTenantEnvironment, environmentID)
	var i GetTenantEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.EnvironmentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantProject = `-- name: GetTenantProject :one
SELECT id::text AS id, organization_id::text AS organization_id, name,
       description, created_at, updated_at
FROM projects
WHERE id = $1::text::uuid
`

type GetTenantProjectRow struct {
	ID             string
	OrganizationID string
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetTenantProject(ctx context.Context, projectID string) (GetTenantProjectRow, error) {
	row := q.db.QueryRow(ctx, getTenantProject, projectID)
	var i GetTenantProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    organization_id, actor_user_id, action, resource_type, resource_id
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    $5::text::uuid
)
`

type InsertAuditLogParams struct {
	OrganizationID string
	ActorUserID    string
	Action         string
	ResourceType   string
	ResourceID     string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const insertTenantRefreshEvent = `-- name: InsertTenantRefreshEvent :exec
INSERT INTO api_refresh_events (
    organization_id, environment_id, event_type, resource_type, resource_id
)
VALUES (
    $1::text::uuid,
    NULLIF($2::text, '')::uuid,
    $3,
    $4,
    $5::text::uuid
)
`

type InsertTenantRefreshEventParams struct {
	OrganizationID string
	EnvironmentID  string
	EventType      string
	ResourceType   string
	ResourceID     string
}

func (q *Queries) InsertTenantRefreshEvent(ctx context.Context, arg InsertTenantRefreshEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantRefreshEvent,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const listAccessibleOrganizations = `-- name: ListAccessibleOrganizations :many
SELECT organizations.id::text AS id, organizations.name, organizations.slug,
       org_members.role, organizations.created_at
FROM organizations
JOIN org_members ON org_members.organization_id = organizations.id
WHERE org_members.user_id = $1::text::uuid
  AND organizations.deleted_at IS NULL
ORDER BY organizations.created_at, organizations.id
LIMIT 100
`

type ListAccessibleOrganizationsRow struct {
	ID        string
	Name      string
	Slug      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAccessibleOrganizations(ctx context.Context, userID string) ([]ListAccessibleOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleOrganizationsRow{}
	for rows.Next() {
		var i ListAccessibleOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantEnvironments = `-- name: ListTenantEnvironments :many
SELECT id::text AS id, organization_id::text AS organization_id,
       project_id::text AS project_id, name, environment_type, created_at, updated_at
FROM environments
WHERE project_id = $1::text::uuid
ORDER BY created_at, id
LIMIT 100
`

type ListTenantEnvironmentsRow struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListTenantEnvironments(ctx context.Context, projectID string) ([]ListTenantEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listTenantEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantEnvironmentsRow{}
	for rows.Next() {
		var i ListTenantEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Name,
			&i.EnvironmentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantProjects = `-- name: ListTenantProjects :many
SELECT id::text AS id, organization_id::text AS organization_id, name,
       description, created_at, updated_at
FROM projects
WHERE organization_id = $1::text::uuid
ORDER BY created_at, id
LIMIT 100
`

type ListTenantProjectsRow struct {
	ID             string
	OrganizationID string
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListTenantProjects(ctx context.Context, organizationID string) ([]ListTenantProjectsRow, error) {
	rows, err := q.db.Query(ctx, listTenantProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantProjectsRow{}
	for rows.Next() {
		var i ListTenantProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationMemberRole = `-- name: LockOrganizationMemberRole :one
SELECT role
FROM org_members
WHERE organization_id = $1::text::uuid
  AND user_id = $2::text::uuid
FOR UPDATE
`

type LockOrganizationMemberRoleParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) LockOrganizationMemberRole(ctx context.Context, arg LockOrganizationMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, lockOrganizationMemberRole, arg.OrganizationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1::text::uuid
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, organizationID)
	return err
}

const updateOrganizationMember = `-- name: UpdateOrganizationMember :one
UPDATE org_members
SET role = $1,
    incident_notifications_enabled = $2,
    updated_at = CURRENT_TIMESTAMP
FROM users
WHERE org_members.organization_id = $3::text::uuid
  AND org_members.user_id = $4::text::uuid
  AND users.id = org_members.user_id
RETURNING org_members.user_id::text AS user_id, users.email, org_members.role,
          org_members.incident_notifications_enabled, org_members.created_at
`

type UpdateOrganizationMemberParams struct {
	Role                         string
	IncidentNotificationsEnabled bool
	OrganizationID               string
	UserID                       string
}

type UpdateOrganizationMemberRow struct {
	UserID                       string
	Email                        string
	Role                         string
	IncidentNotificationsEnabled bool
	CreatedAt                    pgtype.Timestamptz
}

func (q *Queries) UpdateOrganizationMember(ctx context.Context, arg UpdateOrganizationMemberParams) (UpdateOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMember,
		arg.Role,
		arg.IncidentNotificationsEnabled,
		arg.OrganizationID,
		arg.UserID,
	)
	var i UpdateOrganizationMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.IncidentNotificationsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :exec
UPDATE organizations
SET name = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2::text::uuid
  AND deleted_at IS NULL
`

type UpdateOrganizationNameParams struct {
	Name           string
	OrganizationID string
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationName, arg.Name, arg.OrganizationID)
	return err
}

const updateTenantEnvironment = `-- name: UpdateTenantEnvironment :one
UPDATE environments
SET name = $1, environment_type = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::text::uuid
RETURNING id::text AS id, organization_id::text AS organization_id,
          project_id::text AS project_id, name, environment_type, created_at, updated_at
`

type UpdateTenantEnvironmentParams struct {
	Name            string
	EnvironmentType string
	EnvironmentID   string
}

type UpdateTenantEnvironmentRow struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	Name            string
	EnvironmentType string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateTenantEnvironment(ctx context.Context, arg UpdateTenantEnvironmentParams) (UpdateTenantEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, updateTenantEnvironment, arg.Name, arg.EnvironmentType, arg.EnvironmentID)
	var i UpdateTenantEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.EnvironmentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantProject = `-- name: UpdateTenantProject :one
UPDATE projects
SET name = $1, description = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::text::uuid
RETURNING id::text AS id, organization_id::text AS organization_id, name,
          description, created_at, updated_at
`

type UpdateTenantProjectParams struct {
	Name        string
	Description string
	ProjectID   string
}

type UpdateTenantProjectRow struct {
	ID             string
	OrganizationID string
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateTenantProject(ctx context.Context, arg UpdateTenantProjectParams) (UpdateTenantProjectRow, error) {
	row := q.db.QueryRow(ctx, updateTenantProject, arg.Name, arg.Description, arg.ProjectID)
	var i UpdateTenantProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
