// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
