// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_recovery.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuarantineRecord = `-- name: GetQuarantineRecord :one
SELECT queue_kind,
       COALESCE(job_id::text,'')::text AS job_id,
       COALESCE(result_id::text,'')::text AS result_id,
       COALESCE(worker_pool_id,'')::text AS worker_pool_id,
       status,encrypted_payload,redrive_count,expires_at
FROM monitoring_quarantine
WHERE id=$1::uuid
`

type GetQuarantineRecordRow struct {
	QueueKind        string
	JobID            string
	ResultID         string
	WorkerPoolID     string
	Status           string
	EncryptedPayload []byte
	RedriveCount     int16
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) GetQuarantineRecord(ctx context.Context, dollar_1 pgtype.UUID) (GetQuarantineRecordRow, error) {
	row := q.db.QueryRow(ctx, getQuarantineRecord, dollar_1)
	var i GetQuarantineRecordRow
	err := row.Scan(
		&i.QueueKind,
		&i.JobID,
		&i.ResultID,
		&i.WorkerPoolID,
		&i.Status,
		&i.EncryptedPayload,
		&i.RedriveCount,
		&i.ExpiresAt,
	)
	return i, err
}

const getRecoveryResultVerification = `-- name: GetRecoveryResultVerification :one
SELECT COALESCE((SELECT public_material
                 FROM worker_pool_credentials
                 WHERE worker_pool_id=j.worker_pool_id
                   AND purpose='result_signing'
                   AND key_id=$2
                   AND status IN ('active','retired')
                 ORDER BY activates_at DESC
                 LIMIT 1),wp.result_public_key) AS public_key,
       j.state
FROM check_jobs j
JOIN worker_pools wp ON wp.id=j.worker_pool_id
WHERE j.id=$1::uuid AND j.worker_pool_id=$3
`

type GetRecoveryResultVerificationParams struct {
	Column1      pgtype.UUID
	KeyID        string
	WorkerPoolID string
}

type GetRecoveryResultVerificationRow struct {
	PublicKey []byte
	State     string
}

func (q *Queries) GetRecoveryResultVerification(ctx context.Context, arg GetRecoveryResultVerificationParams) (GetRecoveryResultVerificationRow, error) {
	row := q.db.QueryRow(ctx, getRecoveryResultVerification, arg.Column1, arg.KeyID, arg.WorkerPoolID)
	var i GetRecoveryResultVerificationRow
	err := row.Scan(&i.PublicKey, &i.State)
	return i, err
}

const insertQueueRecoveryAudit = `-- name: InsertQueueRecoveryAudit :exec
INSERT INTO worker_pool_audit_events(worker_pool_id,action,actor,reason,safe_details)
VALUES($1,'redrive',$2,$3,jsonb_build_object('quarantine_id',$4::text,'count',1))
`

type InsertQueueRecoveryAuditParams struct {
	WorkerPoolID string
	Actor        string
	Reason       string
	Column4      string
}

func (q *Queries) InsertQueueRecoveryAudit(ctx context.Context, arg InsertQueueRecoveryAuditParams) error {
	_, err := q.db.Exec(ctx, insertQueueRecoveryAudit,
		arg.WorkerPoolID,
		arg.Actor,
		arg.Reason,
		arg.Column4,
	)
	return err
}

const insertQueueRecoveryOperationalEvent = `-- name: InsertQueueRecoveryOperationalEvent :exec
INSERT INTO monitoring_operational_events(event_type,job_id,worker_pool_id,safe_details)
VALUES('redrive',$1::uuid,$2,'controlled result redrive')
`

type InsertQueueRecoveryOperationalEventParams struct {
	Column1      pgtype.UUID
	WorkerPoolID pgtype.Text
}

func (q *Queries) InsertQueueRecoveryOperationalEvent(ctx context.Context, arg InsertQueueRecoveryOperationalEventParams) error {
	_, err := q.db.Exec(ctx, insertQueueRecoveryOperationalEvent, arg.Column1, arg.WorkerPoolID)
	return err
}

const markQuarantineRedriven = `-- name: MarkQuarantineRedriven :execrows
UPDATE monitoring_quarantine
SET status='redriven',redrive_count=redrive_count+1,approver=$2,redrive_reason=$3,reviewed_at=CURRENT_TIMESTAMP
WHERE id=$1::uuid AND status='quarantined' AND redrive_count<3
`

type MarkQuarantineRedrivenParams struct {
	Column1       pgtype.UUID
	Approver      pgtype.Text
	RedriveReason pgtype.Text
}

func (q *Queries) MarkQuarantineRedriven(ctx context.Context, arg MarkQuarantineRedrivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQuarantineRedriven, arg.Column1, arg.Approver, arg.RedriveReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
