// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEnvironmentRefreshEvents = `-- name: ListEnvironmentRefreshEvents :many
SELECT id, event_type, resource_type, resource_id::text AS resource_id, occurred_at
FROM api_refresh_events
WHERE environment_id = $1::text::uuid
  AND id > $2
ORDER BY id
LIMIT $3
`

type ListEnvironmentRefreshEventsParams struct {
	EnvironmentID string
	AfterID       int64
	ResultLimit   int32
}

type ListEnvironmentRefreshEventsRow struct {
	ID           int64
	EventType    string
	ResourceType string
	ResourceID   string
	OccurredAt   pgtype.Timestamptz
}

func (q *Queries) ListEnvironmentRefreshEvents(ctx context.Context, arg ListEnvironmentRefreshEventsParams) ([]ListEnvironmentRefreshEventsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentRefreshEvents, arg.EnvironmentID, arg.AfterID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentRefreshEventsRow{}
	for rows.Next() {
		var i ListEnvironmentRefreshEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
