// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reliability.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceDailyRollupCheckpoint = `-- name: AdvanceDailyRollupCheckpoint :exec
UPDATE monitoring_rollup_checkpoint
SET daily_through = GREATEST(daily_through, $1::text::date),
    updated_at = CURRENT_TIMESTAMP
WHERE singleton
`

func (q *Queries) AdvanceDailyRollupCheckpoint(ctx context.Context, dailyThrough string) error {
	_, err := q.db.Exec(ctx, advanceDailyRollupCheckpoint, dailyThrough)
	return err
}

const advanceHourlyRollupCheckpoint = `-- name: AdvanceHourlyRollupCheckpoint :exec
UPDATE monitoring_rollup_checkpoint
SET hourly_through = GREATEST(hourly_through, $1),
    updated_at = CURRENT_TIMESTAMP
WHERE singleton
`

func (q *Queries) AdvanceHourlyRollupCheckpoint(ctx context.Context, hourlyThrough pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, advanceHourlyRollupCheckpoint, hourlyThrough)
	return err
}

const deleteDailyRollupInvalidations = `-- name: DeleteDailyRollupInvalidations :exec
DELETE FROM monitor_rollup_invalidations
WHERE bucket_kind = 'daily'
  AND bucket_start = $1::text::date
`

func (q *Queries) DeleteDailyRollupInvalidations(ctx context.Context, bucketDate string) error {
	_, err := q.db.Exec(ctx, deleteDailyRollupInvalidations, bucketDate)
	return err
}

const deleteHourlyRollupInvalidations = `-- name: DeleteHourlyRollupInvalidations :exec
DELETE FROM monitor_rollup_invalidations
WHERE bucket_kind = 'hourly'
  AND bucket_start = $1
`

func (q *Queries) DeleteHourlyRollupInvalidations(ctx context.Context, bucketStart pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteHourlyRollupInvalidations, bucketStart)
	return err
}

const deleteReliabilityEvaluationsFrom = `-- name: DeleteReliabilityEvaluationsFrom :exec
DELETE FROM monitor_result_evaluations
WHERE monitor_id = $1::text::uuid
  AND (scheduled_at, job_id) >= (
      $2, $3::text::uuid
  )
`

type DeleteReliabilityEvaluationsFromParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	JobID       string
}

func (q *Queries) DeleteReliabilityEvaluationsFrom(ctx context.Context, arg DeleteReliabilityEvaluationsFromParams) error {
	_, err := q.db.Exec(ctx, deleteReliabilityEvaluationsFrom, arg.MonitorID, arg.ScheduledAt, arg.JobID)
	return err
}

const deleteRetainedCheckJobs = `-- name: DeleteRetainedCheckJobs :execrows
DELETE FROM check_jobs
WHERE (
        (check_jobs.state = 'completed' AND check_jobs.completed_at < $1)
        OR (
            check_jobs.state IN ('dead', 'expired', 'cancelled', 'quarantined')
            AND check_jobs.completed_at < $2
        )
      )
  AND NOT EXISTS (
      SELECT 1 FROM health_checks WHERE health_checks.job_id = check_jobs.id
  )
`

type DeleteRetainedCheckJobsParams struct {
	CompletedBefore   pgtype.Timestamptz
	NonterminalBefore pgtype.Timestamptz
}

func (q *Queries) DeleteRetainedCheckJobs(ctx context.Context, arg DeleteRetainedCheckJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedCheckJobs, arg.CompletedBefore, arg.NonterminalBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetainedCoverageGaps = `-- name: DeleteRetainedCoverageGaps :execrows
DELETE FROM monitoring_coverage_gaps
WHERE scheduled_at < $1
  AND EXISTS (
      SELECT 1
      FROM monitor_rollups_hourly
      WHERE monitor_rollups_hourly.monitor_id = monitoring_coverage_gaps.monitor_id
        AND monitor_rollups_hourly.bucket_start = date_trunc('hour', monitoring_coverage_gaps.scheduled_at)
  )
  AND NOT EXISTS (
      SELECT 1
      FROM monitor_rollup_invalidations
      WHERE monitor_rollup_invalidations.monitor_id = monitoring_coverage_gaps.monitor_id
        AND monitor_rollup_invalidations.bucket_kind = 'hourly'
        AND monitor_rollup_invalidations.bucket_start = date_trunc('hour', monitoring_coverage_gaps.scheduled_at)
  )
`

func (q *Queries) DeleteRetainedCoverageGaps(ctx context.Context, deleteBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedCoverageGaps, deleteBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetainedDailyRollups = `-- name: DeleteRetainedDailyRollups :execrows
DELETE FROM monitor_rollups_daily
WHERE bucket_start < $1::text::date
`

func (q *Queries) DeleteRetainedDailyRollups(ctx context.Context, deleteBefore string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedDailyRollups, deleteBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetainedHealthChecks = `-- name: DeleteRetainedHealthChecks :execrows
DELETE FROM health_checks
WHERE scheduled_at < $1
  AND EXISTS (
      SELECT 1
      FROM monitor_rollups_hourly
      WHERE monitor_rollups_hourly.monitor_id = health_checks.monitor_id
        AND monitor_rollups_hourly.bucket_start = date_trunc('hour', health_checks.scheduled_at)
  )
  AND NOT EXISTS (
      SELECT 1
      FROM monitor_rollup_invalidations
      WHERE monitor_rollup_invalidations.monitor_id = health_checks.monitor_id
        AND monitor_rollup_invalidations.bucket_kind = 'hourly'
        AND monitor_rollup_invalidations.bucket_start = date_trunc('hour', health_checks.scheduled_at)
  )
`

func (q *Queries) DeleteRetainedHealthChecks(ctx context.Context, deleteBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedHealthChecks, deleteBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetainedHourlyRollups = `-- name: DeleteRetainedHourlyRollups :execrows
DELETE FROM monitor_rollups_hourly
WHERE monitor_rollups_hourly.bucket_start < $1
  AND EXISTS (
      SELECT 1
      FROM monitor_rollups_daily
      WHERE monitor_rollups_daily.monitor_id = monitor_rollups_hourly.monitor_id
        AND monitor_rollups_daily.bucket_start = monitor_rollups_hourly.bucket_start::date
  )
  AND NOT EXISTS (
      SELECT 1
      FROM monitor_rollup_invalidations
      WHERE monitor_rollup_invalidations.monitor_id = monitor_rollups_hourly.monitor_id
        AND monitor_rollup_invalidations.bucket_kind = 'daily'
        AND monitor_rollup_invalidations.bucket_start = monitor_rollups_hourly.bucket_start::date
  )
`

func (q *Queries) DeleteRetainedHourlyRollups(ctx context.Context, deleteBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetainedHourlyRollups, deleteBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureMonitorReliabilityState = `-- name: EnsureMonitorReliabilityState :exec
INSERT INTO monitor_reliability_states (monitor_id)
SELECT id
FROM monitors
WHERE id = $1::text::uuid
ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureMonitorReliabilityState(ctx context.Context, monitorID string) error {
	_, err := q.db.Exec(ctx, ensureMonitorReliabilityState, monitorID)
	return err
}

const getMonitorAlertThresholds = `-- name: GetMonitorAlertThresholds :one
SELECT failure_threshold, recovery_threshold
FROM alert_rules
WHERE monitor_id = $1::text::uuid
  AND rule_key = 'consecutive_failures'
  AND enabled
`

type GetMonitorAlertThresholdsRow struct {
	FailureThreshold  int16
	RecoveryThreshold int16
}

func (q *Queries) GetMonitorAlertThresholds(ctx context.Context, monitorID string) (GetMonitorAlertThresholdsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorAlertThresholds, monitorID)
	var i GetMonitorAlertThresholdsRow
	err := row.Scan(&i.FailureThreshold, &i.RecoveryThreshold)
	return i, err
}

const getMonitorEvaluationAtSlot = `-- name: GetMonitorEvaluationAtSlot :one
SELECT observed_state, job_id::text AS job_id
FROM monitor_result_evaluations
WHERE monitor_id = $1::text::uuid
  AND scheduled_at = $2
ORDER BY job_id DESC
LIMIT 1
`

type GetMonitorEvaluationAtSlotParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
}

type GetMonitorEvaluationAtSlotRow struct {
	ObservedState string
	JobID         string
}

func (q *Queries) GetMonitorEvaluationAtSlot(ctx context.Context, arg GetMonitorEvaluationAtSlotParams) (GetMonitorEvaluationAtSlotRow, error) {
	row := q.db.QueryRow(ctx, getMonitorEvaluationAtSlot, arg.MonitorID, arg.ScheduledAt)
	var i GetMonitorEvaluationAtSlotRow
	err := row.Scan(&i.ObservedState, &i.JobID)
	return i, err
}

const getMonitorReliabilityReport = `-- name: GetMonitorReliabilityReport :one
WITH expected_slots AS (
    SELECT slot
    FROM monitor_schedule_periods AS periods
    CROSS JOIN LATERAL generate_series(
        periods.first_slot_at
          + GREATEST(
              0,
              ceil(EXTRACT(EPOCH FROM ($1 - periods.first_slot_at))
                   / periods.interval_seconds)::bigint
            ) * make_interval(secs => periods.interval_seconds),
        LEAST(COALESCE(periods.ends_at, $2), $2)
          - INTERVAL '1 microsecond',
        make_interval(secs => periods.interval_seconds)
    ) AS slots(slot)
    WHERE periods.monitor_id = $3::text::uuid
      AND periods.starts_at < $2
      AND COALESCE(periods.ends_at, $2) > $1
      AND slots.slot >= GREATEST($1, periods.starts_at)
), aggregate AS (
    SELECT count(*)::bigint AS expected,
           count(health_checks.job_id)::bigint AS observed,
           count(health_checks.job_id) FILTER (WHERE health_checks.succeeded)::bigint AS successful
    FROM expected_slots
    LEFT JOIN health_checks
      ON health_checks.monitor_id = $3::text::uuid
     AND health_checks.job_type = 'scheduled'
     AND health_checks.scheduled_at = expected_slots.slot
)
SELECT expected, observed, successful
FROM aggregate
`

type GetMonitorReliabilityReportParams struct {
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
	MonitorID string
}

type GetMonitorReliabilityReportRow struct {
	Expected   int64
	Observed   int64
	Successful int64
}

func (q *Queries) GetMonitorReliabilityReport(ctx context.Context, arg GetMonitorReliabilityReportParams) (GetMonitorReliabilityReportRow, error) {
	row := q.db.QueryRow(ctx, getMonitorReliabilityReport, arg.FromAt, arg.ToAt, arg.MonitorID)
	var i GetMonitorReliabilityReportRow
	err := row.Scan(&i.Expected, &i.Observed, &i.Successful)
	return i, err
}

const getNewestExpectedMonitorSlot = `-- name: GetNewestExpectedMonitorSlot :one
SELECT slot::timestamptz AS slot
FROM monitor_schedule_periods AS periods
CROSS JOIN LATERAL generate_series(
    periods.first_slot_at,
    LEAST(
        COALESCE(periods.ends_at - INTERVAL '1 microsecond', $1::timestamptz),
        $1::timestamptz
    ),
    make_interval(secs => periods.interval_seconds)
) AS slots(slot)
WHERE periods.monitor_id = $2::text::uuid
  AND periods.starts_at <= $1::timestamptz
ORDER BY slot DESC
LIMIT 1
`

type GetNewestExpectedMonitorSlotParams struct {
	EvaluatedAt pgtype.Timestamptz
	MonitorID   string
}

func (q *Queries) GetNewestExpectedMonitorSlot(ctx context.Context, arg GetNewestExpectedMonitorSlotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNewestExpectedMonitorSlot, arg.EvaluatedAt, arg.MonitorID)
	var slot pgtype.Timestamptz
	err := row.Scan(&slot)
	return slot, err
}

const getNextRepairableRollupInvalidation = `-- name: GetNextRepairableRollupInvalidation :one
SELECT bucket_kind, bucket_start
FROM monitor_rollup_invalidations AS invalidation
WHERE bucket_kind = 'hourly'
   OR NOT EXISTS (
       SELECT 1
       FROM monitor_rollup_invalidations AS hourly
       WHERE hourly.bucket_kind = 'hourly'
         AND hourly.bucket_start >= invalidation.bucket_start
         AND hourly.bucket_start < invalidation.bucket_start + INTERVAL '1 day'
   )
ORDER BY CASE bucket_kind WHEN 'hourly' THEN 0 ELSE 1 END, bucket_start
LIMIT 1
`

type GetNextRepairableRollupInvalidationRow struct {
	BucketKind  string
	BucketStart pgtype.Timestamptz
}

func (q *Queries) GetNextRepairableRollupInvalidation(ctx context.Context) (GetNextRepairableRollupInvalidationRow, error) {
	row := q.db.QueryRow(ctx, getNextRepairableRollupInvalidation)
	var i GetNextRepairableRollupInvalidationRow
	err := row.Scan(&i.BucketKind, &i.BucketStart)
	return i, err
}

const getReliabilityBaselineBefore = `-- name: GetReliabilityBaselineBefore :one
SELECT observed_state,
       consecutive_failures,
       consecutive_successes,
       scheduled_at,
       job_id::text AS job_id
FROM monitor_result_evaluations
WHERE monitor_id = $1::text::uuid
  AND (scheduled_at, job_id) < (
      $2, $3::text::uuid
  )
ORDER BY scheduled_at DESC, job_id DESC
LIMIT 1
`

type GetReliabilityBaselineBeforeParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	JobID       string
}

type GetReliabilityBaselineBeforeRow struct {
	ObservedState        string
	ConsecutiveFailures  int16
	ConsecutiveSuccesses int16
	ScheduledAt          pgtype.Timestamptz
	JobID                string
}

func (q *Queries) GetReliabilityBaselineBefore(ctx context.Context, arg GetReliabilityBaselineBeforeParams) (GetReliabilityBaselineBeforeRow, error) {
	row := q.db.QueryRow(ctx, getReliabilityBaselineBefore, arg.MonitorID, arg.ScheduledAt, arg.JobID)
	var i GetReliabilityBaselineBeforeRow
	err := row.Scan(
		&i.ObservedState,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.ScheduledAt,
		&i.JobID,
	)
	return i, err
}

const hasHourlyRollupInvalidationsForDay = `-- name: HasHourlyRollupInvalidationsForDay :one
SELECT EXISTS (
    SELECT 1
    FROM monitor_rollup_invalidations
    WHERE bucket_kind = 'hourly'
      AND bucket_start >= $1::text::date
      AND bucket_start < $1::text::date + INTERVAL '1 day'
) AS has_invalidations
`

func (q *Queries) HasHourlyRollupInvalidationsForDay(ctx context.Context, bucketDate string) (bool, error) {
	row := q.db.QueryRow(ctx, hasHourlyRollupInvalidationsForDay, bucketDate)
	var has_invalidations bool
	err := row.Scan(&has_invalidations)
	return has_invalidations, err
}

const insertMonitorStateCorrection = `-- name: InsertMonitorStateCorrection :exec
INSERT INTO monitor_state_correction_events (
    monitor_id, accepted_job_id, corrected_from,
    previous_display_state, corrected_display_state
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    $5
)
ON CONFLICT (monitor_id, accepted_job_id) DO NOTHING
`

type InsertMonitorStateCorrectionParams struct {
	MonitorID             string
	AcceptedJobID         string
	CorrectedFrom         pgtype.Timestamptz
	PreviousDisplayState  string
	CorrectedDisplayState string
}

func (q *Queries) InsertMonitorStateCorrection(ctx context.Context, arg InsertMonitorStateCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertMonitorStateCorrection,
		arg.MonitorID,
		arg.AcceptedJobID,
		arg.CorrectedFrom,
		arg.PreviousDisplayState,
		arg.CorrectedDisplayState,
	)
	return err
}

const listAllScheduledHealthChecks = `-- name: ListAllScheduledHealthChecks :many
SELECT job_id::text AS job_id, scheduled_at, succeeded
FROM health_checks
WHERE monitor_id = $1::text::uuid
  AND job_type = 'scheduled'
ORDER BY scheduled_at, job_id
`

type ListAllScheduledHealthChecksRow struct {
	JobID       string
	ScheduledAt pgtype.Timestamptz
	Succeeded   bool
}

func (q *Queries) ListAllScheduledHealthChecks(ctx context.Context, monitorID string) ([]ListAllScheduledHealthChecksRow, error) {
	rows, err := q.db.Query(ctx, listAllScheduledHealthChecks, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllScheduledHealthChecksRow{}
	for rows.Next() {
		var i ListAllScheduledHealthChecksRow
		if err := rows.Scan(&i.JobID, &i.ScheduledAt, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsDueForStateRefresh = `-- name: ListMonitorsDueForStateRefresh :many
SELECT DISTINCT monitors.id::text AS monitor_id
FROM monitors
JOIN monitor_schedule_periods
  ON monitor_schedule_periods.monitor_id = monitors.id
WHERE monitors.deleted_at IS NULL
  AND monitor_schedule_periods.starts_at <= $1
ORDER BY monitor_id
LIMIT $2
`

type ListMonitorsDueForStateRefreshParams struct {
	EvaluatedAt pgtype.Timestamptz
	ResultLimit int32
}

func (q *Queries) ListMonitorsDueForStateRefresh(ctx context.Context, arg ListMonitorsDueForStateRefreshParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMonitorsDueForStateRefresh, arg.EvaluatedAt, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var monitor_id string
		if err := rows.Scan(&monitor_id); err != nil {
			return nil, err
		}
		items = append(items, monitor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledHealthChecksAfter = `-- name: ListScheduledHealthChecksAfter :many
SELECT job_id::text AS job_id, scheduled_at, succeeded
FROM health_checks
WHERE monitor_id = $1::text::uuid
  AND job_type = 'scheduled'
  AND (scheduled_at, job_id) > (
      $2, $3::text::uuid
  )
ORDER BY scheduled_at, job_id
`

type ListScheduledHealthChecksAfterParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	JobID       string
}

type ListScheduledHealthChecksAfterRow struct {
	JobID       string
	ScheduledAt pgtype.Timestamptz
	Succeeded   bool
}

func (q *Queries) ListScheduledHealthChecksAfter(ctx context.Context, arg ListScheduledHealthChecksAfterParams) ([]ListScheduledHealthChecksAfterRow, error) {
	rows, err := q.db.Query(ctx, listScheduledHealthChecksAfter, arg.MonitorID, arg.ScheduledAt, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledHealthChecksAfterRow{}
	for rows.Next() {
		var i ListScheduledHealthChecksAfterRow
		if err := rows.Scan(&i.JobID, &i.ScheduledAt, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledHealthChecksFrom = `-- name: ListScheduledHealthChecksFrom :many
SELECT job_id::text AS job_id, scheduled_at, succeeded
FROM health_checks
WHERE monitor_id = $1::text::uuid
  AND job_type = 'scheduled'
  AND (scheduled_at, job_id) >= (
      $2, $3::text::uuid
  )
ORDER BY scheduled_at, job_id
`

type ListScheduledHealthChecksFromParams struct {
	MonitorID   string
	ScheduledAt pgtype.Timestamptz
	JobID       string
}

type ListScheduledHealthChecksFromRow struct {
	JobID       string
	ScheduledAt pgtype.Timestamptz
	Succeeded   bool
}

func (q *Queries) ListScheduledHealthChecksFrom(ctx context.Context, arg ListScheduledHealthChecksFromParams) ([]ListScheduledHealthChecksFromRow, error) {
	rows, err := q.db.Query(ctx, listScheduledHealthChecksFrom, arg.MonitorID, arg.ScheduledAt, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledHealthChecksFromRow{}
	for rows.Next() {
		var i ListScheduledHealthChecksFromRow
		if err := rows.Scan(&i.JobID, &i.ScheduledAt, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDailyRollupCheckpoint = `-- name: LockDailyRollupCheckpoint :one
SELECT daily_through
FROM monitoring_rollup_checkpoint
WHERE singleton
FOR UPDATE
`

func (q *Queries) LockDailyRollupCheckpoint(ctx context.Context) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lockDailyRollupCheckpoint)
	var daily_through pgtype.Date
	err := row.Scan(&daily_through)
	return daily_through, err
}

const lockHourlyRollupCheckpoint = `-- name: LockHourlyRollupCheckpoint :one
SELECT hourly_through
FROM monitoring_rollup_checkpoint
WHERE singleton
FOR UPDATE
`

func (q *Queries) LockHourlyRollupCheckpoint(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lockHourlyRollupCheckpoint)
	var hourly_through pgtype.Timestamptz
	err := row.Scan(&hourly_through)
	return hourly_through, err
}

const lockMonitorReliabilityState = `-- name: LockMonitorReliabilityState :one
SELECT display_state,
       observed_state,
       consecutive_failures,
       consecutive_successes,
       last_observed_scheduled_at,
       COALESCE(last_observed_job_id::text, '')::text AS last_observed_job_id,
       last_evaluated_scheduled_at,
       COALESCE(last_evaluated_job_id::text, '')::text AS last_evaluated_job_id
FROM monitor_reliability_states
WHERE monitor_id = $1::text::uuid
FOR UPDATE
`

type LockMonitorReliabilityStateRow struct {
	DisplayState             string
	ObservedState            string
	ConsecutiveFailures      int16
	ConsecutiveSuccesses     int16
	LastObservedScheduledAt  pgtype.Timestamptz
	LastObservedJobID        string
	LastEvaluatedScheduledAt pgtype.Timestamptz
	LastEvaluatedJobID       string
}

func (q *Queries) LockMonitorReliabilityState(ctx context.Context, monitorID string) (LockMonitorReliabilityStateRow, error) {
	row := q.db.QueryRow(ctx, lockMonitorReliabilityState, monitorID)
	var i LockMonitorReliabilityStateRow
	err := row.Scan(
		&i.DisplayState,
		&i.ObservedState,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastObservedScheduledAt,
		&i.LastObservedJobID,
		&i.LastEvaluatedScheduledAt,
		&i.LastEvaluatedJobID,
	)
	return i, err
}

const recordRetentionCheckpoint = `-- name: RecordRetentionCheckpoint :exec
UPDATE monitoring_rollup_checkpoint
SET last_retention_at = $1, updated_at = CURRENT_TIMESTAMP
WHERE singleton
`

func (q *Queries) RecordRetentionCheckpoint(ctx context.Context, retainedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, recordRetentionCheckpoint, retainedAt)
	return err
}

const updateMonitorReliabilityState = `-- name: UpdateMonitorReliabilityState :exec
UPDATE monitor_reliability_states
SET display_state = $1,
    observed_state = $2,
    consecutive_failures = $3,
    consecutive_successes = $4,
    last_observed_scheduled_at = $5,
    last_observed_job_id = NULLIF($6::text, '')::uuid,
    newest_expected_scheduled_at = $7,
    last_evaluated_scheduled_at = $7,
    last_evaluated_job_id = NULLIF($8::text, '')::uuid,
    updated_at = CURRENT_TIMESTAMP
WHERE monitor_id = $9::text::uuid
`

type UpdateMonitorReliabilityStateParams struct {
	DisplayState              string
	ObservedState             string
	ConsecutiveFailures       int16
	ConsecutiveSuccesses      int16
	LastObservedScheduledAt   pgtype.Timestamptz
	LastObservedJobID         string
	NewestExpectedScheduledAt pgtype.Timestamptz
	LastEvaluatedJobID        string
	MonitorID                 string
}

func (q *Queries) UpdateMonitorReliabilityState(ctx context.Context, arg UpdateMonitorReliabilityStateParams) error {
	_, err := q.db.Exec(ctx, updateMonitorReliabilityState,
		arg.DisplayState,
		arg.ObservedState,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
		arg.LastObservedScheduledAt,
		arg.LastObservedJobID,
		arg.NewestExpectedScheduledAt,
		arg.LastEvaluatedJobID,
		arg.MonitorID,
	)
	return err
}

const upsertDailyMonitorRollups = `-- name: UpsertDailyMonitorRollups :execrows
INSERT INTO monitor_rollups_daily (
    organization_id, environment_id, monitor_id, bucket_start,
    expected_checks, observed_checks, successful_checks, unknown_checks,
    total_duration_microseconds, updated_at
)
SELECT organization_id,
       environment_id,
       monitor_id,
       $1::text::date,
       sum(expected_checks),
       sum(observed_checks),
       sum(successful_checks),
       sum(unknown_checks),
       sum(total_duration_microseconds),
       CURRENT_TIMESTAMP
FROM monitor_rollups_hourly
WHERE bucket_start >= $1::text::date
  AND bucket_start < $1::text::date + INTERVAL '1 day'
GROUP BY organization_id, environment_id, monitor_id
ON CONFLICT (monitor_id, bucket_start)
DO UPDATE SET expected_checks = EXCLUDED.expected_checks,
              observed_checks = EXCLUDED.observed_checks,
              successful_checks = EXCLUDED.successful_checks,
              unknown_checks = EXCLUDED.unknown_checks,
              total_duration_microseconds = EXCLUDED.total_duration_microseconds,
              updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertDailyMonitorRollups(ctx context.Context, bucketDate string) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDailyMonitorRollups, bucketDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertHourlyMonitorRollups = `-- name: UpsertHourlyMonitorRollups :execrows
WITH expected_slots AS (
    SELECT periods.organization_id,
           periods.environment_id,
           periods.monitor_id,
           slot
    FROM monitor_schedule_periods AS periods
    CROSS JOIN LATERAL generate_series(
        periods.first_slot_at
          + GREATEST(
              0,
              ceil(EXTRACT(EPOCH FROM ($1 - periods.first_slot_at))
                   / periods.interval_seconds)::bigint
            ) * make_interval(secs => periods.interval_seconds),
        LEAST(
            COALESCE(
                periods.ends_at,
                LEAST($1 + INTERVAL '1 hour', CURRENT_TIMESTAMP)
            ),
            LEAST($1 + INTERVAL '1 hour', CURRENT_TIMESTAMP)
        ) - INTERVAL '1 microsecond',
        make_interval(secs => periods.interval_seconds)
    ) AS slots(slot)
    WHERE periods.starts_at < LEAST(
              $1 + INTERVAL '1 hour', CURRENT_TIMESTAMP
          )
      AND COALESCE(
              periods.ends_at,
              LEAST($1 + INTERVAL '1 hour', CURRENT_TIMESTAMP)
          ) > $1
      AND slots.slot >= GREATEST($1, periods.starts_at)
), aggregate AS (
    SELECT expected_slots.organization_id,
           expected_slots.environment_id,
           expected_slots.monitor_id,
           count(*)::integer AS expected_checks,
           count(health_checks.job_id)::integer AS observed_checks,
           count(health_checks.job_id) FILTER (WHERE health_checks.succeeded)::integer AS successful_checks,
           COALESCE(sum(health_checks.total_duration_microseconds), 0)::bigint AS total_duration_microseconds
    FROM expected_slots
    LEFT JOIN health_checks
      ON health_checks.monitor_id = expected_slots.monitor_id
     AND health_checks.job_type = 'scheduled'
     AND health_checks.scheduled_at = expected_slots.slot
    GROUP BY expected_slots.organization_id,
             expected_slots.environment_id,
             expected_slots.monitor_id
)
INSERT INTO monitor_rollups_hourly (
    organization_id, environment_id, monitor_id, bucket_start,
    expected_checks, observed_checks, successful_checks, unknown_checks,
    total_duration_microseconds, updated_at
)
SELECT organization_id,
       environment_id,
       monitor_id,
       $1,
       expected_checks,
       observed_checks,
       successful_checks,
       GREATEST(expected_checks - observed_checks, 0),
       total_duration_microseconds,
       CURRENT_TIMESTAMP
FROM aggregate
ON CONFLICT (monitor_id, bucket_start)
DO UPDATE SET expected_checks = EXCLUDED.expected_checks,
              observed_checks = EXCLUDED.observed_checks,
              successful_checks = EXCLUDED.successful_checks,
              unknown_checks = EXCLUDED.unknown_checks,
              total_duration_microseconds = EXCLUDED.total_duration_microseconds,
              updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertHourlyMonitorRollups(ctx context.Context, bucketStart pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, upsertHourlyMonitorRollups, bucketStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMonitorEvaluationPosition = `-- name: UpsertMonitorEvaluationPosition :exec
INSERT INTO monitor_evaluation_positions (
    monitor_id, last_scheduled_at, last_job_id, invalidated_from
)
VALUES (
    $1::text::uuid,
    $2,
    NULLIF($3::text, '')::uuid,
    NULL
)
ON CONFLICT (monitor_id)
DO UPDATE SET last_scheduled_at = EXCLUDED.last_scheduled_at,
              last_job_id = EXCLUDED.last_job_id,
              invalidated_from = NULL,
              updated_at = CURRENT_TIMESTAMP
`

type UpsertMonitorEvaluationPositionParams struct {
	MonitorID       string
	LastScheduledAt pgtype.Timestamptz
	LastJobID       string
}

func (q *Queries) UpsertMonitorEvaluationPosition(ctx context.Context, arg UpsertMonitorEvaluationPositionParams) error {
	_, err := q.db.Exec(ctx, upsertMonitorEvaluationPosition, arg.MonitorID, arg.LastScheduledAt, arg.LastJobID)
	return err
}

const upsertMonitorResultEvaluation = `-- name: UpsertMonitorResultEvaluation :exec
INSERT INTO monitor_result_evaluations (
    monitor_id, job_id, scheduled_at, succeeded, observed_state,
    consecutive_failures, consecutive_successes
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (job_id)
DO UPDATE SET observed_state = EXCLUDED.observed_state,
              consecutive_failures = EXCLUDED.consecutive_failures,
              consecutive_successes = EXCLUDED.consecutive_successes,
              evaluated_at = CURRENT_TIMESTAMP
`

type UpsertMonitorResultEvaluationParams struct {
	MonitorID            string
	JobID                string
	ScheduledAt          pgtype.Timestamptz
	Succeeded            bool
	ObservedState        string
	ConsecutiveFailures  int16
	ConsecutiveSuccesses int16
}

func (q *Queries) UpsertMonitorResultEvaluation(ctx context.Context, arg UpsertMonitorResultEvaluationParams) error {
	_, err := q.db.Exec(ctx, upsertMonitorResultEvaluation,
		arg.MonitorID,
		arg.JobID,
		arg.ScheduledAt,
		arg.Succeeded,
		arg.ObservedState,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
	)
	return err
}
