// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMonitorSchedule = `-- name: AdvanceMonitorSchedule :execrows
UPDATE monitors
SET next_check_at = $1
WHERE organization_id = $2::text::uuid
  AND environment_id = $3::text::uuid
  AND id = $4::text::uuid
  AND next_check_at = $5
`

type AdvanceMonitorScheduleParams struct {
	NextCheckAt    pgtype.Timestamptz
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	ScheduledAt    pgtype.Timestamptz
}

func (q *Queries) AdvanceMonitorSchedule(ctx context.Context, arg AdvanceMonitorScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceMonitorSchedule,
		arg.NextCheckAt,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.ScheduledAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createScheduledCheckJob = `-- name: CreateScheduledCheckJob :execrows
INSERT INTO check_jobs (
    organization_id,
    environment_id,
    monitor_id,
    job_type,
    state,
    scheduled_at
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    'scheduled',
    'pending',
    $4
)
ON CONFLICT (monitor_id, scheduled_at) DO NOTHING
`

type CreateScheduledCheckJobParams struct {
	OrganizationID string
	EnvironmentID  string
	MonitorID      string
	ScheduledAt    pgtype.Timestamptz
}

func (q *Queries) CreateScheduledCheckJob(ctx context.Context, arg CreateScheduledCheckJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, createScheduledCheckJob,
		arg.OrganizationID,
		arg.EnvironmentID,
		arg.MonitorID,
		arg.ScheduledAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockDueMonitors = `-- name: LockDueMonitors :many
SELECT
    monitors.id::text AS monitor_id,
    monitors.organization_id::text AS organization_id,
    monitors.environment_id::text AS environment_id,
    monitors.interval_seconds,
    monitors.next_check_at,
    CURRENT_TIMESTAMP::timestamptz AS scheduler_time
FROM monitors
WHERE monitors.next_check_at <= CURRENT_TIMESTAMP
  AND NOT EXISTS (
      SELECT 1
      FROM check_jobs
      WHERE check_jobs.monitor_id = monitors.id
        AND check_jobs.job_type = 'scheduled'
        AND check_jobs.state IN ('pending', 'running')
  )
ORDER BY monitors.next_check_at, monitors.id
LIMIT $1
FOR UPDATE OF monitors SKIP LOCKED
`

type LockDueMonitorsRow struct {
	MonitorID       string
	OrganizationID  string
	EnvironmentID   string
	IntervalSeconds int32
	NextCheckAt     pgtype.Timestamptz
	SchedulerTime   pgtype.Timestamptz
}

func (q *Queries) LockDueMonitors(ctx context.Context, batchSize int32) ([]LockDueMonitorsRow, error) {
	rows, err := q.db.Query(ctx, lockDueMonitors, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDueMonitorsRow{}
	for rows.Next() {
		var i LockDueMonitorsRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.OrganizationID,
			&i.EnvironmentID,
			&i.IntervalSeconds,
			&i.NextCheckAt,
			&i.SchedulerTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
