// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workerpool.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePendingWorkerPoolCredentials = `-- name: ActivatePendingWorkerPoolCredentials :exec
UPDATE worker_pool_credentials SET status='active'
WHERE worker_pool_id=$1 AND status='pending'
`

func (q *Queries) ActivatePendingWorkerPoolCredentials(ctx context.Context, workerPoolID string) error {
	_, err := q.db.Exec(ctx, activatePendingWorkerPoolCredentials, workerPoolID)
	return err
}

const activateWorkerPool = `-- name: ActivateWorkerPool :exec
UPDATE worker_pools
SET enabled=true,lifecycle_state='active',manifest_digest=$2,updated_at=CURRENT_TIMESTAMP
WHERE id=$1
`

type ActivateWorkerPoolParams struct {
	ID             string
	ManifestDigest []byte
}

func (q *Queries) ActivateWorkerPool(ctx context.Context, arg ActivateWorkerPoolParams) error {
	_, err := q.db.Exec(ctx, activateWorkerPool, arg.ID, arg.ManifestDigest)
	return err
}

const deleteWorkerPool = `-- name: DeleteWorkerPool :exec
DELETE FROM worker_pools WHERE id=$1
`

func (q *Queries) DeleteWorkerPool(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkerPool, id)
	return err
}

const failWorkerPool = `-- name: FailWorkerPool :exec
UPDATE worker_pools
SET enabled=false,lifecycle_state='failed',updated_at=CURRENT_TIMESTAMP
WHERE id=$1
`

func (q *Queries) FailWorkerPool(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, failWorkerPool, id)
	return err
}

const insertWorkerPoolAudit = `-- name: InsertWorkerPoolAudit :exec
INSERT INTO worker_pool_audit_events(worker_pool_id,action,actor,reason)
VALUES($1,$2,$3,$4)
`

type InsertWorkerPoolAuditParams struct {
	WorkerPoolID string
	Action       string
	Actor        string
	Reason       string
}

func (q *Queries) InsertWorkerPoolAudit(ctx context.Context, arg InsertWorkerPoolAuditParams) error {
	_, err := q.db.Exec(ctx, insertWorkerPoolAudit,
		arg.WorkerPoolID,
		arg.Action,
		arg.Actor,
		arg.Reason,
	)
	return err
}

const insertWorkerPoolCredential = `-- name: InsertWorkerPoolCredential :exec
INSERT INTO worker_pool_credentials(worker_pool_id,purpose,key_id,public_material,fingerprint,status,activates_at)
VALUES($1,$2,$3,$4,$5,'pending',CURRENT_TIMESTAMP)
`

type InsertWorkerPoolCredentialParams struct {
	WorkerPoolID   string
	Purpose        string
	KeyID          string
	PublicMaterial []byte
	Fingerprint    string
}

func (q *Queries) InsertWorkerPoolCredential(ctx context.Context, arg InsertWorkerPoolCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWorkerPoolCredential,
		arg.WorkerPoolID,
		arg.Purpose,
		arg.KeyID,
		arg.PublicMaterial,
		arg.Fingerprint,
	)
	return err
}

const insertWorkerPoolDriftEvent = `-- name: InsertWorkerPoolDriftEvent :exec
INSERT INTO monitoring_operational_events(event_type,worker_pool_id,safe_details)
VALUES('pool_drift',$1,$2)
`

type InsertWorkerPoolDriftEventParams struct {
	WorkerPoolID pgtype.Text
	SafeDetails  string
}

func (q *Queries) InsertWorkerPoolDriftEvent(ctx context.Context, arg InsertWorkerPoolDriftEventParams) error {
	_, err := q.db.Exec(ctx, insertWorkerPoolDriftEvent, arg.WorkerPoolID, arg.SafeDetails)
	return err
}

const insertWorkerPoolMTLSCredential = `-- name: InsertWorkerPoolMTLSCredential :exec
INSERT INTO worker_pool_credentials(worker_pool_id,purpose,key_id,fingerprint,status,activates_at,not_after)
VALUES($1,'mtls_certificate',$2,$3,'pending',CURRENT_TIMESTAMP,$4)
`

type InsertWorkerPoolMTLSCredentialParams struct {
	WorkerPoolID string
	KeyID        string
	Fingerprint  string
	NotAfter     pgtype.Timestamptz
}

func (q *Queries) InsertWorkerPoolMTLSCredential(ctx context.Context, arg InsertWorkerPoolMTLSCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWorkerPoolMTLSCredential,
		arg.WorkerPoolID,
		arg.KeyID,
		arg.Fingerprint,
		arg.NotAfter,
	)
	return err
}

const lockWorkerPoolActivationReadiness = `-- name: LockWorkerPoolActivationReadiness :one
SELECT lifecycle_state='provisioning'
       AND job_queue_url IS NOT NULL
       AND job_queue_arn IS NOT NULL
       AND job_dlq_url IS NOT NULL
       AND job_dlq_arn IS NOT NULL
       AND encryption_public_key IS NOT NULL
       AND result_public_key IS NOT NULL
       AND (SELECT count(*)=CASE WHEN worker_pools.mode='customer_vpc' THEN 3 ELSE 2 END
            FROM worker_pool_credentials c
            WHERE c.worker_pool_id=worker_pools.id
              AND c.status='pending'
              AND (c.purpose<>'mtls_certificate' OR c.not_after>CURRENT_TIMESTAMP+INTERVAL '10 days')) AS ready
FROM worker_pools
WHERE worker_pools.id=$1
FOR UPDATE
`

func (q *Queries) LockWorkerPoolActivationReadiness(ctx context.Context, id string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, lockWorkerPoolActivationReadiness, id)
	var ready pgtype.Bool
	err := row.Scan(&ready)
	return ready, err
}

const lockWorkerPoolDeletionState = `-- name: LockWorkerPoolDeletionState :one
SELECT lifecycle_state,
       (SELECT count(*)::bigint FROM check_jobs WHERE check_jobs.worker_pool_id=$1 AND state IN ('pending','pending_publish','published','running')) AS jobs,
       (SELECT count(*)::bigint FROM worker_pool_credentials WHERE worker_pool_credentials.worker_pool_id=$1 AND status<>'revoked' AND (not_after IS NULL OR not_after>CURRENT_TIMESTAMP)) AS trusted_credentials
FROM worker_pools
WHERE worker_pools.id=$1
FOR UPDATE
`

type LockWorkerPoolDeletionStateRow struct {
	LifecycleState     string
	Jobs               int64
	TrustedCredentials int64
}

func (q *Queries) LockWorkerPoolDeletionState(ctx context.Context, workerPoolID string) (LockWorkerPoolDeletionStateRow, error) {
	row := q.db.QueryRow(ctx, lockWorkerPoolDeletionState, workerPoolID)
	var i LockWorkerPoolDeletionStateRow
	err := row.Scan(&i.LifecycleState, &i.Jobs, &i.TrustedCredentials)
	return i, err
}

const lockWorkerPoolLifecycleState = `-- name: LockWorkerPoolLifecycleState :one
SELECT lifecycle_state FROM worker_pools WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockWorkerPoolLifecycleState(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkerPoolLifecycleState, id)
	var lifecycle_state string
	err := row.Scan(&lifecycle_state)
	return lifecycle_state, err
}

const lockWorkerPoolManifestDigest = `-- name: LockWorkerPoolManifestDigest :one
SELECT manifest_digest FROM worker_pools WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockWorkerPoolManifestDigest(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockWorkerPoolManifestDigest, id)
	var manifest_digest []byte
	err := row.Scan(&manifest_digest)
	return manifest_digest, err
}

const registerWorkerPool = `-- name: RegisterWorkerPool :exec
INSERT INTO worker_pools(id,mode,enabled,lifecycle_state,schema_min,schema_max,encryption_key_id,encryption_public_key,result_key_id,result_public_key,job_queue_url,job_queue_arn,job_dlq_url,job_dlq_arn)
VALUES($1,$2,false,'provisioning',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type RegisterWorkerPoolParams struct {
	ID                  string
	Mode                string
	SchemaMin           int16
	SchemaMax           int16
	EncryptionKeyID     pgtype.Text
	EncryptionPublicKey []byte
	ResultKeyID         pgtype.Text
	ResultPublicKey     []byte
	JobQueueUrl         pgtype.Text
	JobQueueArn         pgtype.Text
	JobDlqUrl           pgtype.Text
	JobDlqArn           pgtype.Text
}

func (q *Queries) RegisterWorkerPool(ctx context.Context, arg RegisterWorkerPoolParams) error {
	_, err := q.db.Exec(ctx, registerWorkerPool,
		arg.ID,
		arg.Mode,
		arg.SchemaMin,
		arg.SchemaMax,
		arg.EncryptionKeyID,
		arg.EncryptionPublicKey,
		arg.ResultKeyID,
		arg.ResultPublicKey,
		arg.JobQueueUrl,
		arg.JobQueueArn,
		arg.JobDlqUrl,
		arg.JobDlqArn,
	)
	return err
}

const revokeWorkerPoolCredentials = `-- name: RevokeWorkerPoolCredentials :exec
UPDATE worker_pool_credentials
SET status='revoked',revoked_at=CURRENT_TIMESTAMP
WHERE worker_pool_id=$1 AND status IN ('pending','active','retired')
`

func (q *Queries) RevokeWorkerPoolCredentials(ctx context.Context, workerPoolID string) error {
	_, err := q.db.Exec(ctx, revokeWorkerPoolCredentials, workerPoolID)
	return err
}

const updateWorkerPoolLifecycle = `-- name: UpdateWorkerPoolLifecycle :exec
UPDATE worker_pools
SET lifecycle_state=$2,enabled=false,updated_at=CURRENT_TIMESTAMP
WHERE id=$1
`

type UpdateWorkerPoolLifecycleParams struct {
	ID             string
	LifecycleState string
}

func (q *Queries) UpdateWorkerPoolLifecycle(ctx context.Context, arg UpdateWorkerPoolLifecycleParams) error {
	_, err := q.db.Exec(ctx, updateWorkerPoolLifecycle, arg.ID, arg.LifecycleState)
	return err
}
